In [1]:
# 라이브러리 불러오기
import os
import pandas as pd

In [2]:
BASE_DIR = os.getcwd()
BASE_DIR

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\CCTV'

In [3]:
DATA_PATH = os.path.join(BASE_DIR, 'input', 'cctv_busan.csv')
DATA_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\CCTV\\input\\cctv_busan.csv'

In [4]:
OUTPUT_PATH = os.path.join(BASE_DIR, 'output', 'cctv_busan_filter.csv')
OUTPUT_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\CCTV\\output\\cctv_busan_filter.csv'

In [5]:
df_raw = pd.read_csv(DATA_PATH, encoding='cp949')
df_raw.head()

,개방자치단체코드,관리번호,관리기관명,소재지도로명주소,소재지지번주소,설치목적구분,카메라대수,카메라화소수,촬영방면정보,보관일수,설치연월,관리기관전화번호,WGS84위도,WGS84경도,데이터기준일자,데이터갱신구분,데이터갱신시점,최종수정시점
0,3250000,202632500000800382,부산광역시 중구청,부산광역시 중구 광복로49번길 26,부산광역시 중구 광복로49번길 26,생활방범,1,200.0,360도 전방면,30.0,201312.0,051-600-4171,35.10148,129.03033,2026-05-07,I,2026-05-15 18:45:39,2026-05-07 15:39:48
1,3250000,202632500000800383,부산광역시 중구청,부산광역시 중구 영주로6번안길 3,부산광역시 중구 영주로6번안길 3,생활방범,1,200.0,360도 전방면,30.0,201312.0,051-600-4171,35.11060,129.03273,2026-05-07,I,2026-05-15 18:45:39,2026-05-07 15:39:48
2,3250000,202632500000800384,부산광역시 중구청,부산광역시 중구 망양로355번길 10,부산광역시 중구 망양로355번길 10,생활방범,1,200.0,360도 전방면,30.0,201312.0,051-600-4171,35.10826,129.03047,2026-05-07,I,2026-05-15 18:45:39,2026-05-07 15:39:48
3,3250000,202632500000800385,부산광역시 중구청,부산광역시 중구 중구로185번길 7,부산광역시 중구 중구로185번길 7,생활방범,1,200.0,360도 전방면,30.0,201312.0,051-600-4171,35.11148,129.03375,2026-05-07,I,2026-05-15 18:45:39,2026-05-07 15:39:48
4,3250000,202632500000800375,부산광역시 중구청,부산광역시 중구 동광길 74,부산광역시 중구 동광길 74,생활방범,1,200.0,360도 전방면,30.0,201411.0,051-600-4171,35.10595,129.03497,2026-05-07,I,2026-05-15 18:45:39,2026-05-07 15:39:48

In [6]:
df_busan = df_raw[['관리기관명', '카메라대수', '설치연월']]
df_busan = df_busan.reset_index(drop=True)

In [53]:
df_busan.head()

       관리기관명  카메라대수      설치연월
0  부산광역시 중구청      1  201312.0
1  부산광역시 중구청      1  201312.0
2  부산광역시 중구청      1  201312.0
3  부산광역시 중구청      1  201312.0
4  부산광역시 중구청      1  201411.0

In [8]:
df_busan.shape

(18074, 3)

In [54]:
df_busan = df_raw[df_raw['관리기관명'].str.contains('부산')].copy()
df_busan['설치연도'] = df_busan['설치연월'].dropna().astype(str).str[:4]
result = df_busan.groupby('설치연도')['카메라대수'].sum().reset_index()
print(result)

    설치연도  카메라대수
0   2001    247
1   2003     21
2   2006     33
3   2007     30
4   2008     32
5   2009     39
6   2010    170
7   2011    135
8   2012    637
9   2013    491
10  2014    516
11  2015    581
12  2016    858
13  2017    727
14  2018    759
15  2019   1239
16  2020   1263
17  2021    948
18  2022    992
19  2023   1010
20  2024    906
21  2025   1309
22  2026     81

In [57]:
result['설치연도'] = result['설치연도'].astype(int)

df_busan_filter = result[(result['설치연도']>=2019)&(result['설치연도']<=2026)].copy()

df_busan_filter['누적카메라대수'] = result['카메라대수'].cumsum()

print(df_busan_filter)

    설치연도  카메라대수  누적카메라대수
15  2019   1239     6515
16  2020   1263     7778
17  2021    948     8726
18  2022    992     9718
19  2023   1010    10728
20  2024    906    11634
21  2025   1309    12943
22  2026     81    13024

In [56]:
# CSV 저장

df_busan_filter.to_csv(OUTPUT_PATH, encoding='utf-8-sig', index=False)

print('csv 저장 완료!')
print(f'경로: {OUTPUT_PATH}')
print(f'크기: {len(df_busan_filter):,}행 x {len(df_busan_filter.columns)}열')

csv 저장 완료!
경로: c:\Users\Administrator\bigdata2026\fastapi\CCTV\output\cctv_busan_filter.csv
크기: 4행 x 3열