In [44]:
import math
import os
import time
from datetime import date
import pandas as pd
import requests
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

In [45]:
load_dotenv()
API_KEY = os.getenv('TAGO_API_KEK')

if API_KEY:
    print(f'API 키 로드 완료: {API_KEY[:6]}...{API_KEY[-4:]}')
else:
    print('env파일에 API키를 설정하세요.')

API 키 로드 완료: fcaf4c...4bf3

In [46]:
BASE_URL = 'https://apis.data.go.kr/1613000/BusSttnInfoInqireService/getSttnThrghRouteList'

response = requests.get(BASE_URL, 
                        params={
                            'serviceKey': API_KEY,
                            'pageNo': 1,
                            'numOfRows':10,
                            'cityCode': 22,
                            'nodeId' : 'DGB7041046200',
                            '_type': 'json'
                            })    # 대구가 22
response

In [47]:
BASE_DIR = os.getcwd()  # 현재 위치
OUTPUT_DIR = os.path.join(BASE_DIR, 'output')
OUTPUT_PATH = os.path.join(OUTPUT_DIR, 'route_by_stop.csv')

In [48]:
DB_URL = 'postgresql://postgres:1234@localhost:5432/busapidb'
TABLE_NAME = 'route_by_stop'

print(f'csv저장경로 : {OUTPUT_PATH}')

csv저장경로 : c:\Users\Administrator\bigdata2026\fastapi\03_bus_api_pipeline\output\route_by_stop.csv

In [49]:
data = response.json()
data

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
  'body': {'items': {'item': [{'endnodenm': '매곡(종점)',
      'routeid': 'DGB1000001000',
      'routeno': '급행1',
      'routetp': '급행버스',
      'startnodenm': '동화시설집단지구(종점)1'},
     {'endnodenm': '북구 동호동(종점)2(서리지입구)',
      'routeid': 'DGB1000002001',
      'routeno': '급행2',
      'routetp': '급행버스',
      'startnodenm': '냉천전원음식점지구'},
     {'endnodenm': '동명교통',
      'routeid': 'DGB1000003000',
      'routeno': '급행3',
      'routetp': '급행버스',
      'startnodenm': '범물1동행정복지센터건너'},
     {'endnodenm': '신흥버스',
      'routeid': 'DGB1000005000',
      'routeno': '급행5',
      'routetp': '급행버스',
      'startnodenm': '대구대(정문1)'},
     {'endnodenm': '북구 동호동(종점)2(서리지입구)',
      'routeid': 'DGB1000007000',
      'routeno': '급행7',
      'routetp': '급행버스',
      'startnodenm': '남도버스1'},
     {'endnodenm': '서대구역(남측)2',
      'routeid': 'DGB1000008004',
      'routeno': '급행8',
      'routetp': '급행버스',
      'startnodenm': '기업은행국가산단지점건너'},
     {'endnodenm': '진천역(2번출구)',
      'routeid': 'DGB1000008101',
      'routeno': '급행8-1',
      'routetp': '급행버스',
      'startnodenm': '유곡리공영차고지앞'},
     {'endnodenm': '군위군청',
      'routeid': 'DGB1000009002',
      'routeno': '급행9',
      'routetp': '급행버스',
      'startnodenm': '북구 동호동(종점)1'},
     {'endnodenm': '우보버스정류장',
      'routeid': 'DGB1000009100',
      'routeno': '급행9-1',
      'routetp': '급행버스',
      'startnodenm': '북구 동호동(종점)1'},
     {'endnodenm': '삼국유사면문화관',
      'routeid': 'DGB1000009200',
      'routeno': '급행9-2',
      'routetp': '급행버스',
      'startnodenm': '북구 동호동(종점)1'}]},
   'numOfRows': 10,
   'pageNo': 1,
   'totalCount': 232}}}

In [50]:
data['response']['body']['items']['item']

[{'endnodenm': '매곡(종점)',
  'routeid': 'DGB1000001000',
  'routeno': '급행1',
  'routetp': '급행버스',
  'startnodenm': '동화시설집단지구(종점)1'},
 {'endnodenm': '북구 동호동(종점)2(서리지입구)',
  'routeid': 'DGB1000002001',
  'routeno': '급행2',
  'routetp': '급행버스',
  'startnodenm': '냉천전원음식점지구'},
 {'endnodenm': '동명교통',
  'routeid': 'DGB1000003000',
  'routeno': '급행3',
  'routetp': '급행버스',
  'startnodenm': '범물1동행정복지센터건너'},
 {'endnodenm': '신흥버스',
  'routeid': 'DGB1000005000',
  'routeno': '급행5',
  'routetp': '급행버스',
  'startnodenm': '대구대(정문1)'},
 {'endnodenm': '북구 동호동(종점)2(서리지입구)',
  'routeid': 'DGB1000007000',
  'routeno': '급행7',
  'routetp': '급행버스',
  'startnodenm': '남도버스1'},
 {'endnodenm': '서대구역(남측)2',
  'routeid': 'DGB1000008004',
  'routeno': '급행8',
  'routetp': '급행버스',
  'startnodenm': '기업은행국가산단지점건너'},
 {'endnodenm': '진천역(2번출구)',
  'routeid': 'DGB1000008101',
  'routeno': '급행8-1',
  'routetp': '급행버스',
  'startnodenm': '유곡리공영차고지앞'},
 {'endnodenm': '군위군청',
  'routeid': 'DGB1000009002',
  'routeno': '급행9',
  'routetp': '급행버스',
  'startnodenm': '북구 동호동(종점)1'},
 {'endnodenm': '우보버스정류장',
  'routeid': 'DGB1000009100',
  'routeno': '급행9-1',
  'routetp': '급행버스',
  'startnodenm': '북구 동호동(종점)1'},
 {'endnodenm': '삼국유사면문화관',
  'routeid': 'DGB1000009200',
  'routeno': '급행9-2',
  'routetp': '급행버스',
  'startnodenm': '북구 동호동(종점)1'}]

In [51]:
BASE_URL = 'https://apis.data.go.kr/1613000/BusSttnInfoInqireService/getSttnThrghRouteList'
CITY_CODE = 22
NODE_ID = 'DGB7041046600'
ROWS_PER_PAGE = 100
REQUEST_TIMEOUT = 10

In [52]:
data['response']['body']['totalCount']

232

In [53]:
total_count = data['response']['body']['totalCount']
total_pages = math.ceil(total_count / ROWS_PER_PAGE)

print(f'전체 건수 : {total_count:,}개')
print(f'페이지당 건수 {ROWS_PER_PAGE:,}개')
print(f'총 페이지 수 : {total_pages}페이지')

전체 건수 : 232개
페이지당 건수 100개
총 페이지 수 : 3페이지

In [54]:
all_items = []

for page_no in range(1, total_pages+1):
    params={
        'serviceKey' : API_KEY,
        'pageNo' : page_no,
        'numOfRows' : ROWS_PER_PAGE,
        'cityCode' : CITY_CODE,
        '_type' : 'json',
        'nodeid': NODE_ID
    }

    response = requests.get(BASE_URL, params=params,timeout=REQUEST_TIMEOUT)
    response.raise_for_status()

    page_body = response.json()['response']['body']

    #마지막 페이지나 오류 상황에서는 items가 비어있을 수 있다.

    if not page_body.get('items'):
        print(f'{page_no} / {total_pages} 페이지 : 페이지가 없음')
        continue # 아래로 내려가지 않고, 다음 페이지(순서로) 간다

    page_items = page_body['items'].get('item',[])  # 없으면 빈 리스트

    if isinstance(page_items, dict):
        page_items = [page_items]   # 딕셔너리가 맞다면 리스트 형태로 저장

    all_items.extend(page_items)    # 여러개를 맨 뒤에 한꺼번에 추가하는 리스트함수

    print(f'{page_no} / {total_pages} 페이지 수집 완료 -> 누적 {len(all_items):,}건')

    time.sleep(0.2) # 너무 빠르게 요청하지 않게 0.2초 기다린 후 다음 진행

print(f'전체 수집 완료 : {len(all_items):,}건')

ReadTimeout: HTTPSConnectionPool(host='apis.data.go.kr', port=443): Read timed out. (read timeout=10)

In [ ]:
df_raw = pd.DataFrame(all_items)

print(f'데이터프레임의 크기 : {df_raw.shape}')
print(f'컬럼 목록 : {df_raw.columns.tolist()}')

데이터프레임의 크기 : (5, 5)
컬럼 목록 : ['endnodenm', 'routeid', 'routeno', 'routetp', 'startnodenm']

In [ ]:
df_raw.head()

       endnodenm        routeid routeno routetp startnodenm
0         매곡(종점)  DGB4070003008     성서3    지선버스         연화리
1         매곡(종점)  DGB4070003000     성서3    지선버스         연화리
2  화원유원지(사문진주막촌)  DGB4030003002     달서3    지선버스        신흥버스
3         매곡(종점)  DGB4070003003     성서3    지선버스         연화리
4         매곡(종점)  DGB4070003011     성서3    지선버스         연화리

In [ ]:
COLUMN_RENAME = {
    'endnodenm'  : '종점',
    'routeid'    : '노선ID',
    'routeno'    : '노선번호',
    'routetp'    : '노선유형',
    'startnodenm'   : '기점',
}
df = df_raw.rename(columns=COLUMN_RENAME)

print(f'변경 후 컬럼 목록 : {df.columns.tolist()}')
df.head()

변경 후 컬럼 목록 : ['종점', '노선ID', '노선번호', '노선유형', '기점']

              종점           노선ID 노선번호  노선유형    기점
0         매곡(종점)  DGB4070003008  성서3  지선버스   연화리
1         매곡(종점)  DGB4070003000  성서3  지선버스   연화리
2  화원유원지(사문진주막촌)  DGB4030003002  달서3  지선버스  신흥버스
3         매곡(종점)  DGB4070003003  성서3  지선버스   연화리
4         매곡(종점)  DGB4070003011  성서3  지선버스   연화리

In [ ]:
df['정류장ID'] = NODE_ID
df

              종점           노선ID 노선번호  노선유형    기점          정류장ID
0         매곡(종점)  DGB4070003008  성서3  지선버스   연화리  DGB7041046600
1         매곡(종점)  DGB4070003000  성서3  지선버스   연화리  DGB7041046600
2  화원유원지(사문진주막촌)  DGB4030003002  달서3  지선버스  신흥버스  DGB7041046600
3         매곡(종점)  DGB4070003003  성서3  지선버스   연화리  DGB7041046600
4         매곡(종점)  DGB4070003011  성서3  지선버스   연화리  DGB7041046600

In [ ]:
# 함수 정의
def save_to_postgresql(df, db_url, table_name):
    """DataFrame을 PostgreSQL 테이블로 저장하는 함수"""
    df_save = df.copy()

    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)

    engine = create_engine(db_url)

    # DB 연결 테스트
    with engine.connect() as conn:
        version = conn.execute(text('SELECT version();')).fetchone()[0]
        print('PostgreSQL 연결 성공!')
        print(version[:80] + '...')

    # DataFrame을 DB테이블로 저장
    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize=1000,
        method='multi'
    )

    # 저장 건수 확인
    with engine.connect() as conn:
        saved_count = conn.execute(text(f'SELECT COUNT(*) FROM {table_name};')).fetchone()[0]

    print(f'저장 완료: {saved_count:,}행')
    print(f'DB: busapidb / table: {table_name}')

In [55]:
save_to_postgresql(df, DB_URL, TABLE_NAME)

PostgreSQL 연결 성공!
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
저장 완료: 5행
DB: busapidb / table: route_by_stop