In [151]:
import pandas as pd
from sqlalchemy import create_engine, text
import os

BASE_DIR = os.getcwd()
BASE_DIR

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\02_parking'

In [152]:
DATA_PATH = os.path.join(BASE_DIR, 'input','parking_raw.csv')
DATA_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\02_parking\\input\\parking_raw.csv'

In [153]:
OUTPUT_PATH = os.path.join(BASE_DIR,'output','parking_long.csv')
OUTPUT_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\02_parking\\output\\parking_long.csv'

In [154]:
DB_URL = 'postgresql://postgres:1234@localhost:5432/parkingdb'

In [155]:
df_raw = pd.read_csv(DATA_PATH, encoding='cp949')
df_raw.head()

,순번,주차장관리번호,주차장명,주차장 유형,소재지지번주소,주차구획수,급지구분,부제시행구분,운영요일,평일운영시작시각,...,주차기본요금,추가단위시간,추가단위요금,1일주차권요금적용시간,1일주차권적용시간,월정기요금,결제방법,관리기관명,경도,위도
0,1,154-1-000001,3공단로25길인근,노상,대구광역시 북구 노원동3가 191-1,6,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.897770,128.565410
1,2,154-1-000002,3공단로인근,노상,대구광역시 북구 노원동3가 14,329,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시청,35.899471,128.569853
2,3,154-1-000003,검단동로인근,노상,대구광역시 북구 검단동 745-2,29,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.913949,128.625135
3,4,154-1-000004,경대로17길인근,노상,대구광역시 북구 복현동 573,78,2,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.892740,128.612720
4,5,154-1-000005,경대로23길인근,노상,대구광역시 북구 복현동 606-34,5,2,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.892602,128.616021

In [156]:
df_raw.columns.tolist()

['순번',
 '주차장관리번호',
 '주차장명',
 '주차장 유형',
 '소재지지번주소',
 '주차구획수',
 '급지구분',
 '부제시행구분',
 '운영요일',
 '평일운영시작시각',
 '평일운영종료시각',
 '토요일운영시작시각',
 '토요일운영종료시각',
 '공휴일운영시작시각',
 '공유일운영종료시각',
 '요금정보',
 '주차기본시간',
 '주차기본요금',
 '추가단위시간',
 '추가단위요금',
 '1일주차권요금적용시간',
 '1일주차권적용시간',
 '월정기요금',
 '결제방법',
 '관리기관명',
 '경도',
 '위도']

In [157]:
df_raw.shape

(229, 27)

In [158]:
df_long = df_raw[['주차장명','소재지지번주소','주차구획수']]
df_long = df_long.reset_index(drop=True)

In [159]:
df_long.head()

        주차장명               소재지지번주소  주차구획수
0  3공단로25길인근  대구광역시 북구 노원동3가 191-1      6
1     3공단로인근     대구광역시 북구 노원동3가 14    329
2     검단동로인근    대구광역시 북구 검단동 745-2     29
3   경대로17길인근      대구광역시 북구 복현동 573     78
4   경대로23길인근   대구광역시 북구 복현동 606-34      5

In [160]:
def df_long_PK(count):
    if count < 20:
        return '소형'
    elif count > 50 :
        return '대형'
    else:
        return '중형'
    
df_long['규모구분'] = df_long['주차구획수'].apply(df_long_PK)

df_long.head()

        주차장명               소재지지번주소  주차구획수 규모구분
0  3공단로25길인근  대구광역시 북구 노원동3가 191-1      6   소형
1     3공단로인근     대구광역시 북구 노원동3가 14    329   대형
2     검단동로인근    대구광역시 북구 검단동 745-2     29   중형
3   경대로17길인근      대구광역시 북구 복현동 573     78   대형
4   경대로23길인근   대구광역시 북구 복현동 606-34      5   소형

In [161]:
df_raw['요금정보']

0      무료
1      무료
2      무료
3      무료
4      무료
       ..
224    유료
225    유료
226    유료
227    유료
228    유료
Name: 요금정보, Length: 229, dtype: str

In [162]:
df_long['요금정보'] = df_raw['요금정보'].copy
df_long.head()

,주차장명,소재지지번주소,주차구획수,규모구분,요금정보
0,3공단로25길인근,대구광역시 북구 노원동3가 191-1,6,소형,<bound method NDFrame.copy of 0 무료\n1 ...
1,3공단로인근,대구광역시 북구 노원동3가 14,329,대형,<bound method NDFrame.copy of 0 무료\n1 ...
2,검단동로인근,대구광역시 북구 검단동 745-2,29,중형,<bound method NDFrame.copy of 0 무료\n1 ...
3,경대로17길인근,대구광역시 북구 복현동 573,78,대형,<bound method NDFrame.copy of 0 무료\n1 ...
4,경대로23길인근,대구광역시 북구 복현동 606-34,5,소형,<bound method NDFrame.copy of 0 무료\n1 ...

In [163]:
def df_long_money(fee):
    if fee=='무료':
        return '무료'
    else:
        return '유료'
    
df_long['fee_type'] = df_raw['요금정보'].apply(df_long_money)

df_long.head()

,주차장명,소재지지번주소,주차구획수,규모구분,요금정보,fee_type
0,3공단로25길인근,대구광역시 북구 노원동3가 191-1,6,소형,<bound method NDFrame.copy of 0 무료\n1 ...,무료
1,3공단로인근,대구광역시 북구 노원동3가 14,329,대형,<bound method NDFrame.copy of 0 무료\n1 ...,무료
2,검단동로인근,대구광역시 북구 검단동 745-2,29,중형,<bound method NDFrame.copy of 0 무료\n1 ...,무료
3,경대로17길인근,대구광역시 북구 복현동 573,78,대형,<bound method NDFrame.copy of 0 무료\n1 ...,무료
4,경대로23길인근,대구광역시 북구 복현동 606-34,5,소형,<bound method NDFrame.copy of 0 무료\n1 ...,무료

In [164]:
def save_to_postgresql(df, db_url, table_name):
    df_save = df.copy()

    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)

    engine= create_engine(db_url)

    with engine.connect() as conn:
        version = conn.execute(text('SELECT version();')).fetchone()[0]
        print('POSTGRESQL 연결 성공!')
        print(version[:80] + '...')

    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize=1000,
        method='multi'
    )

    with engine.connect() as conn:
        saved_count = conn.execute(text(f'SELECT COUNT(*) FROM {table_name};')).fetchone()[0]

    print(f'저장 완료! {saved_count:,}행')
    print(f'DB : parking_lot / table : {table_name}')

In [165]:
TABLE_NAME = 'subway_raw'

In [166]:
save_to_postgresql(df_long,DB_URL,TABLE_NAME)

POSTGRESQL 연결 성공!
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...

DatabaseError: Execution failed on sql 'INSERT INTO subway_raw ("주차장명", "소재지지번주소", "주차구획수", "규모구분", "요금정보", fee_type) VALUES (:주차장명_m0, :소재지지번주소_m0, :주차구획수_m0, :규모구분_m0, :요금정보_m0, :fee_type_m0), (:주차장명_m1, :소재지지번주소_m1, :주차구획수_m1, :규모구분_m1, :요금정보_m1, :fee_type_m1), (:주차장명_m2, :소재지지번주소_m2, :주차구획수_m2, :규모구분_m2, :요금정보_m2, :fee_type_m2), (:주차장명_m3, :소재지지번주소_m3, :주차구획수_m3, :규모구분_m3, :요금정보_m3, :fee_type_m3), (:주차장명_m4, :소재지지번주소_m4, :주차구획수_m4, :규모구분_m4, :요금정보_m4, :fee_type_m4), (:주차장명_m5, :소재지지번주소_m5, :주차구획수_m5, :규모구분_m5, :요금정보_m5, :fee_type_m5), (:주차장명_m6, :소재지지번주소_m6, :주차구획수_m6, :규모구분_m6, :요금정보_m6, :fee_type_m6), (:주차장명_m7, :소재지지번주소_m7, :주차구획수_m7, :규모구분_m7, :요금정보_m7, :fee_type_m7), (:주차장명_m8, :소재지지번주소_m8, :주차구획수_m8, :규모구분_m8, :요금정보_m8, :fee_type_m8), (:주차장명_m9, :소재지지번주소_m9, :주차구획수_m9, :규모구분_m9, :요금정보_m9, :fee_type_m9), (:주차장명_m10, :소재지지번주소_m10, :주차구획수_m10, :규모구분_m10, :요금정보_m10, :fee_type_m10), (:주차장명_m11, :소재지지번주소_m11, :주차구획수_m11, :규모구분_m11, :요금정보_m11, :fee_type_m11), (:주차장명_m12, :소재지지번주소_m12, :주차구획수_m12, :규모구분_m12, :요금정보_m12, :fee_type_m12), (:주차장명_m13, :소재지지번주소_m13, :주차구획수_m13, :규모구분_m13, :요금정보_m13, :fee_type_m13), (:주차장명_m14, :소재지지번주소_m14, :주차구획수_m14, :규모구분_m14, :요금정보_m14, :fee_type_m14), (:주차장명_m15, :소재지지번주소_m15, :주차구획수_m15, :규모구분_m15, :요금정보_m15, :fee_type_m15), (:주차장명_m16, :소재지지번주소_m16, :주차구획수_m16, :규모구분_m16, :요금정보_m16, :fee_type_m16), (:주차장명_m17, :소재지지번주소_m17, :주차구획수_m17, :규모구분_m17, :요금정보_m17, :fee_type_m17), (:주차장명_m18, :소재지지번주소_m18, :주차구획수_m18, :규모구분_m18, :요금정보_m18, :fee_type_m18), (:주차장명_m19, :소재지지번주소_m19, :주차구획수_m19, :규모구분_m19, :요금정보_m19, :fee_type_m19), (:주차장명_m20, :소재지지번주소_m20, :주차구획수_m20, :규모구분_m20, :요금정보_m20, :fee_type_m20), (:주차장명_m21, :소재지지번주소_m21, :주차구획수_m21, :규모구분_m21, :요금정보_m21, :fee_type_m21), (:주차장명_m22, :소재지지번주소_m22, :주차구획수_m22, :규모구분_m22, :요금정보_m22, :fee_type_m22), (:주차장명_m23, :소재지지번주소_m23, :주차구획수_m23, :규모구분_m23, :요금정보_m23, :fee_type_m23), (:주차장명_m24, :소재지지번주소_m24, :주차구획수_m24, :규모구분_m24, :요금정보_m24, :fee_type_m24), (:주차장명_m25, :소재지지번주소_m25, :주차구획수_m25, :규모구분_m25, :요금정보_m25, :fee_type_m25), (:주차장명_m26, :소재지지번주소_m26, :주차구획수_m26, :규모구분_m26, :요금정보_m26, :fee_type_m26), (:주차장명_m27, :소재지지번주소_m27, :주차구획수_m27, :규모구분_m27, :요금정보_m27, :fee_type_m27), (:주차장명_m28, :소재지지번주소_m28, :주차구획수_m28, :규모구분_m28, :요금정보_m28, :fee_type_m28), (:주차장명_m29, :소재지지번주소_m29, :주차구획수_m29, :규모구분_m29, :요금정보_m29, :fee_type_m29), (:주차장명_m30, :소재지지번주소_m30, :주차구획수_m30, :규모구분_m30, :요금정보_m30, :fee_type_m30), (:주차장명_m31, :소재지지번주소_m31, :주차구획수_m31, :규모구분_m31, :요금정보_m31, :fee_type_m31), (:주차장명_m32, :소재지지번주소_m32, :주차구획수_m32, :규모구분_m32, :요금정보_m32, :fee_type_m32), (:주차장명_m33, :소재지지번주소_m33, :주차구획수_m33, :규모구분_m33, :요금정보_m33, :fee_type_m33), (:주차장명_m34, :소재지지번주소_m34, :주차구획수_m34, :규모구분_m34, :요금정보_m34, :fee_type_m34), (:주차장명_m35, :소재지지번주소_m35, :주차구획수_m35, :규모구분_m35, :요금정보_m35, :fee_type_m35), (:주차장명_m36, :소재지지번주소_m36, :주차구획수_m36, :규모구분_m36, :요금정보_m36, :fee_type_m36), (:주차장명_m37, :소재지지번주소_m37, :주차구획수_m37, :규모구분_m37, :요금정보_m37, :fee_type_m37), (:주차장명_m38, :소재지지번주소_m38, :주차구획수_m38, :규모구분_m38, :요금정보_m38, :fee_type_m38), (:주차장명_m39, :소재지지번주소_m39, :주차구획수_m39, :규모구분_m39, :요금정보_m39, :fee_type_m39), (:주차장명_m40, :소재지지번주소_m40, :주차구획수_m40, :규모구분_m40, :요금정보_m40, :fee_type_m40), (:주차장명_m41, :소재지지번주소_m41, :주차구획수_m41, :규모구분_m41, :요금정보_m41, :fee_type_m41), (:주차장명_m42, :소재지지번주소_m42, :주차구획수_m42, :규모구분_m42, :요금정보_m42, :fee_type_m42), (:주차장명_m43, :소재지지번주소_m43, :주차구획수_m43, :규모구분_m43, :요금정보_m43, :fee_type_m43), (:주차장명_m44, :소재지지번주소_m44, :주차구획수_m44, :규모구분_m44, :요금정보_m44, :fee_type_m44), (:주차장명_m45, :소재지지번주소_m45, :주차구획수_m45, :규모구분_m45, :요금정보_m45, :fee_type_m45), (:주차장명_m46, :소재지지번주소_m46, :주차구획수_m46, :규모구분_m46, :요금정보_m46, :fee_type_m46), (:주차장명_m47, :소재지지번주소_m47, :주차구획수_m47, :규모구분_m47, :요금정보_m47, :fee_type_m47), (:주차장명_m48, :소재지지번주소_m48, :주차구획수_m48, :규모구분_m48, :요금정보_m48, :fee_type_m48), (:주차장명_m49, :소재지지번주소_m49, :주차구획수_m49, :규모구분_m49, :요금정보_m49, :fee_type_m49), (:주차장명_m50, :소재지지번주소_m50, :주차구획수_m50, :규모구분_m50, :요금정보_m50, :fee_type_m50), (:주차장명_m51, :소재지지번주소_m51, :주차구획수_m51, :규모구분_m51, :요금정보_m51, :fee_type_m51), (:주차장명_m52, :소재지지번주소_m52, :주차구획수_m52, :규모구분_m52, :요금정보_m52, :fee_type_m52), (:주차장명_m53, :소재지지번주소_m53, :주차구획수_m53, :규모구분_m53, :요금정보_m53, :fee_type_m53), (:주차장명_m54, :소재지지번주소_m54, :주차구획수_m54, :규모구분_m54, :요금정보_m54, :fee_type_m54), (:주차장명_m55, :소재지지번주소_m55, :주차구획수_m55, :규모구분_m55, :요금정보_m55, :fee_type_m55), (:주차장명_m56, :소재지지번주소_m56, :주차구획수_m56, :규모구분_m56, :요금정보_m56, :fee_type_m56), (:주차장명_m57, :소재지지번주소_m57, :주차구획수_m57, :규모구분_m57, :요금정보_m57, :fee_type_m57), (:주차장명_m58, :소재지지번주소_m58, :주차구획수_m58, :규모구분_m58, :요금정보_m58, :fee_type_m58), (:주차장명_m59, :소재지지번주소_m59, :주차구획수_m59, :규모구분_m59, :요금정보_m59, :fee_type_m59), (:주차장명_m60, :소재지지번주소_m60, :주차구획수_m60, :규모구분_m60, :요금정보_m60, :fee_type_m60), (:주차장명_m61, :소재지지번주소_m61, :주차구획수_m61, :규모구분_m61, :요금정보_m61, :fee_type_m61), (:주차장명_m62, :소재지지번주소_m62, :주차구획수_m62, :규모구분_m62, :요금정보_m62, :fee_type_m62), (:주차장명_m63, :소재지지번주소_m63, :주차구획수_m63, :규모구분_m63, :요금정보_m63, :fee_type_m63), (:주차장명_m64, :소재지지번주소_m64, :주차구획수_m64, :규모구분_m64, :요금정보_m64, :fee_type_m64), (:주차장명_m65, :소재지지번주소_m65, :주차구획수_m65, :규모구분_m65, :요금정보_m65, :fee_type_m65), (:주차장명_m66, :소재지지번주소_m66, :주차구획수_m66, :규모구분_m66, :요금정보_m66, :fee_type_m66), (:주차장명_m67, :소재지지번주소_m67, :주차구획수_m67, :규모구분_m67, :요금정보_m67, :fee_type_m67), (:주차장명_m68, :소재지지번주소_m68, :주차구획수_m68, :규모구분_m68, :요금정보_m68, :fee_type_m68), (:주차장명_m69, :소재지지번주소_m69, :주차구획수_m69, :규모구분_m69, :요금정보_m69, :fee_type_m69), (:주차장명_m70, :소재지지번주소_m70, :주차구획수_m70, :규모구분_m70, :요금정보_m70, :fee_type_m70), (:주차장명_m71, :소재지지번주소_m71, :주차구획수_m71, :규모구분_m71, :요금정보_m71, :fee_type_m71), (:주차장명_m72, :소재지지번주소_m72, :주차구획수_m72, :규모구분_m72, :요금정보_m72, :fee_type_m72), (:주차장명_m73, :소재지지번주소_m73, :주차구획수_m73, :규모구분_m73, :요금정보_m73, :fee_type_m73), (:주차장명_m74, :소재지지번주소_m74, :주차구획수_m74, :규모구분_m74, :요금정보_m74, :fee_type_m74), (:주차장명_m75, :소재지지번주소_m75, :주차구획수_m75, :규모구분_m75, :요금정보_m75, :fee_type_m75), (:주차장명_m76, :소재지지번주소_m76, :주차구획수_m76, :규모구분_m76, :요금정보_m76, :fee_type_m76), (:주차장명_m77, :소재지지번주소_m77, :주차구획수_m77, :규모구분_m77, :요금정보_m77, :fee_type_m77), (:주차장명_m78, :소재지지번주소_m78, :주차구획수_m78, :규모구분_m78, :요금정보_m78, :fee_type_m78), (:주차장명_m79, :소재지지번주소_m79, :주차구획수_m79, :규모구분_m79, :요금정보_m79, :fee_type_m79), (:주차장명_m80, :소재지지번주소_m80, :주차구획수_m80, :규모구분_m80, :요금정보_m80, :fee_type_m80), (:주차장명_m81, :소재지지번주소_m81, :주차구획수_m81, :규모구분_m81, :요금정보_m81, :fee_type_m81), (:주차장명_m82, :소재지지번주소_m82, :주차구획수_m82, :규모구분_m82, :요금정보_m82, :fee_type_m82), (:주차장명_m83, :소재지지번주소_m83, :주차구획수_m83, :규모구분_m83, :요금정보_m83, :fee_type_m83), (:주차장명_m84, :소재지지번주소_m84, :주차구획수_m84, :규모구분_m84, :요금정보_m84, :fee_type_m84), (:주차장명_m85, :소재지지번주소_m85, :주차구획수_m85, :규모구분_m85, :요금정보_m85, :fee_type_m85), (:주차장명_m86, :소재지지번주소_m86, :주차구획수_m86, :규모구분_m86, :요금정보_m86, :fee_type_m86), (:주차장명_m87, :소재지지번주소_m87, :주차구획수_m87, :규모구분_m87, :요금정보_m87, :fee_type_m87), (:주차장명_m88, :소재지지번주소_m88, :주차구획수_m88, :규모구분_m88, :요금정보_m88, :fee_type_m88), (:주차장명_m89, :소재지지번주소_m89, :주차구획수_m89, :규모구분_m89, :요금정보_m89, :fee_type_m89), (:주차장명_m90, :소재지지번주소_m90, :주차구획수_m90, :규모구분_m90, :요금정보_m90, :fee_type_m90), (:주차장명_m91, :소재지지번주소_m91, :주차구획수_m91, :규모구분_m91, :요금정보_m91, :fee_type_m91), (:주차장명_m92, :소재지지번주소_m92, :주차구획수_m92, :규모구분_m92, :요금정보_m92, :fee_type_m92), (:주차장명_m93, :소재지지번주소_m93, :주차구획수_m93, :규모구분_m93, :요금정보_m93, :fee_type_m93), (:주차장명_m94, :소재지지번주소_m94, :주차구획수_m94, :규모구분_m94, :요금정보_m94, :fee_type_m94), (:주차장명_m95, :소재지지번주소_m95, :주차구획수_m95, :규모구분_m95, :요금정보_m95, :fee_type_m95), (:주차장명_m96, :소재지지번주소_m96, :주차구획수_m96, :규모구분_m96, :요금정보_m96, :fee_type_m96), (:주차장명_m97, :소재지지번주소_m97, :주차구획수_m97, :규모구분_m97, :요금정보_m97, :fee_type_m97), (:주차장명_m98, :소재지지번주소_m98, :주차구획수_m98, :규모구분_m98, :요금정보_m98, :fee_type_m98), (:주차장명_m99, :소재지지번주소_m99, :주차구획수_m99, :규모구분_m99, :요금정보_m99, :fee_type_m99), (:주차장명_m100, :소재지지번주소_m100, :주차구획수_m100, :규모구분_m100, :요금정보_m100, :fee_type_m100), (:주차장명_m101, :소재지지번주소_m101, :주차구획수_m101, :규모구분_m101, :요금정보_m101, :fee_type_m101), (:주차장명_m102, :소재지지번주소_m102, :주차구획수_m102, :규모구분_m102, :요금정보_m102, :fee_type_m102), (:주차장명_m103, :소재지지번주소_m103, :주차구획수_m103, :규모구분_m103, :요금정보_m103, :fee_type_m103), (:주차장명_m104, :소재지지번주소_m104, :주차구획수_m104, :규모구분_m104, :요금정보_m104, :fee_type_m104), (:주차장명_m105, :소재지지번주소_m105, :주차구획수_m105, :규모구분_m105, :요금정보_m105, :fee_type_m105), (:주차장명_m106, :소재지지번주소_m106, :주차구획수_m106, :규모구분_m106, :요금정보_m106, :fee_type_m106), (:주차장명_m107, :소재지지번주소_m107, :주차구획수_m107, :규모구분_m107, :요금정보_m107, :fee_type_m107), (:주차장명_m108, :소재지지번주소_m108, :주차구획수_m108, :규모구분_m108, :요금정보_m108, :fee_type_m108), (:주차장명_m109, :소재지지번주소_m109, :주차구획수_m109, :규모구분_m109, :요금정보_m109, :fee_type_m109), (:주차장명_m110, :소재지지번주소_m110, :주차구획수_m110, :규모구분_m110, :요금정보_m110, :fee_type_m110), (:주차장명_m111, :소재지지번주소_m111, :주차구획수_m111, :규모구분_m111, :요금정보_m111, :fee_type_m111), (:주차장명_m112, :소재지지번주소_m112, :주차구획수_m112, :규모구분_m112, :요금정보_m112, :fee_type_m112), (:주차장명_m113, :소재지지번주소_m113, :주차구획수_m113, :규모구분_m113, :요금정보_m113, :fee_type_m113), (:주차장명_m114, :소재지지번주소_m114, :주차구획수_m114, :규모구분_m114, :요금정보_m114, :fee_type_m114), (:주차장명_m115, :소재지지번주소_m115, :주차구획수_m115, :규모구분_m115, :요금정보_m115, :fee_type_m115), (:주차장명_m116, :소재지지번주소_m116, :주차구획수_m116, :규모구분_m116, :요금정보_m116, :fee_type_m116), (:주차장명_m117, :소재지지번주소_m117, :주차구획수_m117, :규모구분_m117, :요금정보_m117, :fee_type_m117), (:주차장명_m118, :소재지지번주소_m118, :주차구획수_m118, :규모구분_m118, :요금정보_m118, :fee_type_m118), (:주차장명_m119, :소재지지번주소_m119, :주차구획수_m119, :규모구분_m119, :요금정보_m119, :fee_type_m119), (:주차장명_m120, :소재지지번주소_m120, :주차구획수_m120, :규모구분_m120, :요금정보_m120, :fee_type_m120), (:주차장명_m121, :소재지지번주소_m121, :주차구획수_m121, :규모구분_m121, :요금정보_m121, :fee_type_m121), (:주차장명_m122, :소재지지번주소_m122, :주차구획수_m122, :규모구분_m122, :요금정보_m122, :fee_type_m122), (:주차장명_m123, :소재지지번주소_m123, :주차구획수_m123, :규모구분_m123, :요금정보_m123, :fee_type_m123), (:주차장명_m124, :소재지지번주소_m124, :주차구획수_m124, :규모구분_m124, :요금정보_m124, :fee_type_m124), (:주차장명_m125, :소재지지번주소_m125, :주차구획수_m125, :규모구분_m125, :요금정보_m125, :fee_type_m125), (:주차장명_m126, :소재지지번주소_m126, :주차구획수_m126, :규모구분_m126, :요금정보_m126, :fee_type_m126), (:주차장명_m127, :소재지지번주소_m127, :주차구획수_m127, :규모구분_m127, :요금정보_m127, :fee_type_m127), (:주차장명_m128, :소재지지번주소_m128, :주차구획수_m128, :규모구분_m128, :요금정보_m128, :fee_type_m128), (:주차장명_m129, :소재지지번주소_m129, :주차구획수_m129, :규모구분_m129, :요금정보_m129, :fee_type_m129), (:주차장명_m130, :소재지지번주소_m130, :주차구획수_m130, :규모구분_m130, :요금정보_m130, :fee_type_m130), (:주차장명_m131, :소재지지번주소_m131, :주차구획수_m131, :규모구분_m131, :요금정보_m131, :fee_type_m131), (:주차장명_m132, :소재지지번주소_m132, :주차구획수_m132, :규모구분_m132, :요금정보_m132, :fee_type_m132), (:주차장명_m133, :소재지지번주소_m133, :주차구획수_m133, :규모구분_m133, :요금정보_m133, :fee_type_m133), (:주차장명_m134, :소재지지번주소_m134, :주차구획수_m134, :규모구분_m134, :요금정보_m134, :fee_type_m134), (:주차장명_m135, :소재지지번주소_m135, :주차구획수_m135, :규모구분_m135, :요금정보_m135, :fee_type_m135), (:주차장명_m136, :소재지지번주소_m136, :주차구획수_m136, :규모구분_m136, :요금정보_m136, :fee_type_m136), (:주차장명_m137, :소재지지번주소_m137, :주차구획수_m137, :규모구분_m137, :요금정보_m137, :fee_type_m137), (:주차장명_m138, :소재지지번주소_m138, :주차구획수_m138, :규모구분_m138, :요금정보_m138, :fee_type_m138), (:주차장명_m139, :소재지지번주소_m139, :주차구획수_m139, :규모구분_m139, :요금정보_m139, :fee_type_m139), (:주차장명_m140, :소재지지번주소_m140, :주차구획수_m140, :규모구분_m140, :요금정보_m140, :fee_type_m140), (:주차장명_m141, :소재지지번주소_m141, :주차구획수_m141, :규모구분_m141, :요금정보_m141, :fee_type_m141), (:주차장명_m142, :소재지지번주소_m142, :주차구획수_m142, :규모구분_m142, :요금정보_m142, :fee_type_m142), (:주차장명_m143, :소재지지번주소_m143, :주차구획수_m143, :규모구분_m143, :요금정보_m143, :fee_type_m143), (:주차장명_m144, :소재지지번주소_m144, :주차구획수_m144, :규모구분_m144, :요금정보_m144, :fee_type_m144), (:주차장명_m145, :소재지지번주소_m145, :주차구획수_m145, :규모구분_m145, :요금정보_m145, :fee_type_m145), (:주차장명_m146, :소재지지번주소_m146, :주차구획수_m146, :규모구분_m146, :요금정보_m146, :fee_type_m146), (:주차장명_m147, :소재지지번주소_m147, :주차구획수_m147, :규모구분_m147, :요금정보_m147, :fee_type_m147), (:주차장명_m148, :소재지지번주소_m148, :주차구획수_m148, :규모구분_m148, :요금정보_m148, :fee_type_m148), (:주차장명_m149, :소재지지번주소_m149, :주차구획수_m149, :규모구분_m149, :요금정보_m149, :fee_type_m149), (:주차장명_m150, :소재지지번주소_m150, :주차구획수_m150, :규모구분_m150, :요금정보_m150, :fee_type_m150), (:주차장명_m151, :소재지지번주소_m151, :주차구획수_m151, :규모구분_m151, :요금정보_m151, :fee_type_m151), (:주차장명_m152, :소재지지번주소_m152, :주차구획수_m152, :규모구분_m152, :요금정보_m152, :fee_type_m152), (:주차장명_m153, :소재지지번주소_m153, :주차구획수_m153, :규모구분_m153, :요금정보_m153, :fee_type_m153), (:주차장명_m154, :소재지지번주소_m154, :주차구획수_m154, :규모구분_m154, :요금정보_m154, :fee_type_m154), (:주차장명_m155, :소재지지번주소_m155, :주차구획수_m155, :규모구분_m155, :요금정보_m155, :fee_type_m155), (:주차장명_m156, :소재지지번주소_m156, :주차구획수_m156, :규모구분_m156, :요금정보_m156, :fee_type_m156), (:주차장명_m157, :소재지지번주소_m157, :주차구획수_m157, :규모구분_m157, :요금정보_m157, :fee_type_m157), (:주차장명_m158, :소재지지번주소_m158, :주차구획수_m158, :규모구분_m158, :요금정보_m158, :fee_type_m158), (:주차장명_m159, :소재지지번주소_m159, :주차구획수_m159, :규모구분_m159, :요금정보_m159, :fee_type_m159), (:주차장명_m160, :소재지지번주소_m160, :주차구획수_m160, :규모구분_m160, :요금정보_m160, :fee_type_m160), (:주차장명_m161, :소재지지번주소_m161, :주차구획수_m161, :규모구분_m161, :요금정보_m161, :fee_type_m161), (:주차장명_m162, :소재지지번주소_m162, :주차구획수_m162, :규모구분_m162, :요금정보_m162, :fee_type_m162), (:주차장명_m163, :소재지지번주소_m163, :주차구획수_m163, :규모구분_m163, :요금정보_m163, :fee_type_m163), (:주차장명_m164, :소재지지번주소_m164, :주차구획수_m164, :규모구분_m164, :요금정보_m164, :fee_type_m164), (:주차장명_m165, :소재지지번주소_m165, :주차구획수_m165, :규모구분_m165, :요금정보_m165, :fee_type_m165), (:주차장명_m166, :소재지지번주소_m166, :주차구획수_m166, :규모구분_m166, :요금정보_m166, :fee_type_m166), (:주차장명_m167, :소재지지번주소_m167, :주차구획수_m167, :규모구분_m167, :요금정보_m167, :fee_type_m167), (:주차장명_m168, :소재지지번주소_m168, :주차구획수_m168, :규모구분_m168, :요금정보_m168, :fee_type_m168), (:주차장명_m169, :소재지지번주소_m169, :주차구획수_m169, :규모구분_m169, :요금정보_m169, :fee_type_m169), (:주차장명_m170, :소재지지번주소_m170, :주차구획수_m170, :규모구분_m170, :요금정보_m170, :fee_type_m170), (:주차장명_m171, :소재지지번주소_m171, :주차구획수_m171, :규모구분_m171, :요금정보_m171, :fee_type_m171), (:주차장명_m172, :소재지지번주소_m172, :주차구획수_m172, :규모구분_m172, :요금정보_m172, :fee_type_m172), (:주차장명_m173, :소재지지번주소_m173, :주차구획수_m173, :규모구분_m173, :요금정보_m173, :fee_type_m173), (:주차장명_m174, :소재지지번주소_m174, :주차구획수_m174, :규모구분_m174, :요금정보_m174, :fee_type_m174), (:주차장명_m175, :소재지지번주소_m175, :주차구획수_m175, :규모구분_m175, :요금정보_m175, :fee_type_m175), (:주차장명_m176, :소재지지번주소_m176, :주차구획수_m176, :규모구분_m176, :요금정보_m176, :fee_type_m176), (:주차장명_m177, :소재지지번주소_m177, :주차구획수_m177, :규모구분_m177, :요금정보_m177, :fee_type_m177), (:주차장명_m178, :소재지지번주소_m178, :주차구획수_m178, :규모구분_m178, :요금정보_m178, :fee_type_m178), (:주차장명_m179, :소재지지번주소_m179, :주차구획수_m179, :규모구분_m179, :요금정보_m179, :fee_type_m179), (:주차장명_m180, :소재지지번주소_m180, :주차구획수_m180, :규모구분_m180, :요금정보_m180, :fee_type_m180), (:주차장명_m181, :소재지지번주소_m181, :주차구획수_m181, :규모구분_m181, :요금정보_m181, :fee_type_m181), (:주차장명_m182, :소재지지번주소_m182, :주차구획수_m182, :규모구분_m182, :요금정보_m182, :fee_type_m182), (:주차장명_m183, :소재지지번주소_m183, :주차구획수_m183, :규모구분_m183, :요금정보_m183, :fee_type_m183), (:주차장명_m184, :소재지지번주소_m184, :주차구획수_m184, :규모구분_m184, :요금정보_m184, :fee_type_m184), (:주차장명_m185, :소재지지번주소_m185, :주차구획수_m185, :규모구분_m185, :요금정보_m185, :fee_type_m185), (:주차장명_m186, :소재지지번주소_m186, :주차구획수_m186, :규모구분_m186, :요금정보_m186, :fee_type_m186), (:주차장명_m187, :소재지지번주소_m187, :주차구획수_m187, :규모구분_m187, :요금정보_m187, :fee_type_m187), (:주차장명_m188, :소재지지번주소_m188, :주차구획수_m188, :규모구분_m188, :요금정보_m188, :fee_type_m188), (:주차장명_m189, :소재지지번주소_m189, :주차구획수_m189, :규모구분_m189, :요금정보_m189, :fee_type_m189), (:주차장명_m190, :소재지지번주소_m190, :주차구획수_m190, :규모구분_m190, :요금정보_m190, :fee_type_m190), (:주차장명_m191, :소재지지번주소_m191, :주차구획수_m191, :규모구분_m191, :요금정보_m191, :fee_type_m191), (:주차장명_m192, :소재지지번주소_m192, :주차구획수_m192, :규모구분_m192, :요금정보_m192, :fee_type_m192), (:주차장명_m193, :소재지지번주소_m193, :주차구획수_m193, :규모구분_m193, :요금정보_m193, :fee_type_m193), (:주차장명_m194, :소재지지번주소_m194, :주차구획수_m194, :규모구분_m194, :요금정보_m194, :fee_type_m194), (:주차장명_m195, :소재지지번주소_m195, :주차구획수_m195, :규모구분_m195, :요금정보_m195, :fee_type_m195), (:주차장명_m196, :소재지지번주소_m196, :주차구획수_m196, :규모구분_m196, :요금정보_m196, :fee_type_m196), (:주차장명_m197, :소재지지번주소_m197, :주차구획수_m197, :규모구분_m197, :요금정보_m197, :fee_type_m197), (:주차장명_m198, :소재지지번주소_m198, :주차구획수_m198, :규모구분_m198, :요금정보_m198, :fee_type_m198), (:주차장명_m199, :소재지지번주소_m199, :주차구획수_m199, :규모구분_m199, :요금정보_m199, :fee_type_m199), (:주차장명_m200, :소재지지번주소_m200, :주차구획수_m200, :규모구분_m200, :요금정보_m200, :fee_type_m200), (:주차장명_m201, :소재지지번주소_m201, :주차구획수_m201, :규모구분_m201, :요금정보_m201, :fee_type_m201), (:주차장명_m202, :소재지지번주소_m202, :주차구획수_m202, :규모구분_m202, :요금정보_m202, :fee_type_m202), (:주차장명_m203, :소재지지번주소_m203, :주차구획수_m203, :규모구분_m203, :요금정보_m203, :fee_type_m203), (:주차장명_m204, :소재지지번주소_m204, :주차구획수_m204, :규모구분_m204, :요금정보_m204, :fee_type_m204), (:주차장명_m205, :소재지지번주소_m205, :주차구획수_m205, :규모구분_m205, :요금정보_m205, :fee_type_m205), (:주차장명_m206, :소재지지번주소_m206, :주차구획수_m206, :규모구분_m206, :요금정보_m206, :fee_type_m206), (:주차장명_m207, :소재지지번주소_m207, :주차구획수_m207, :규모구분_m207, :요금정보_m207, :fee_type_m207), (:주차장명_m208, :소재지지번주소_m208, :주차구획수_m208, :규모구분_m208, :요금정보_m208, :fee_type_m208), (:주차장명_m209, :소재지지번주소_m209, :주차구획수_m209, :규모구분_m209, :요금정보_m209, :fee_type_m209), (:주차장명_m210, :소재지지번주소_m210, :주차구획수_m210, :규모구분_m210, :요금정보_m210, :fee_type_m210), (:주차장명_m211, :소재지지번주소_m211, :주차구획수_m211, :규모구분_m211, :요금정보_m211, :fee_type_m211), (:주차장명_m212, :소재지지번주소_m212, :주차구획수_m212, :규모구분_m212, :요금정보_m212, :fee_type_m212), (:주차장명_m213, :소재지지번주소_m213, :주차구획수_m213, :규모구분_m213, :요금정보_m213, :fee_type_m213), (:주차장명_m214, :소재지지번주소_m214, :주차구획수_m214, :규모구분_m214, :요금정보_m214, :fee_type_m214), (:주차장명_m215, :소재지지번주소_m215, :주차구획수_m215, :규모구분_m215, :요금정보_m215, :fee_type_m215), (:주차장명_m216, :소재지지번주소_m216, :주차구획수_m216, :규모구분_m216, :요금정보_m216, :fee_type_m216), (:주차장명_m217, :소재지지번주소_m217, :주차구획수_m217, :규모구분_m217, :요금정보_m217, :fee_type_m217), (:주차장명_m218, :소재지지번주소_m218, :주차구획수_m218, :규모구분_m218, :요금정보_m218, :fee_type_m218), (:주차장명_m219, :소재지지번주소_m219, :주차구획수_m219, :규모구분_m219, :요금정보_m219, :fee_type_m219), (:주차장명_m220, :소재지지번주소_m220, :주차구획수_m220, :규모구분_m220, :요금정보_m220, :fee_type_m220), (:주차장명_m221, :소재지지번주소_m221, :주차구획수_m221, :규모구분_m221, :요금정보_m221, :fee_type_m221), (:주차장명_m222, :소재지지번주소_m222, :주차구획수_m222, :규모구분_m222, :요금정보_m222, :fee_type_m222), (:주차장명_m223, :소재지지번주소_m223, :주차구획수_m223, :규모구분_m223, :요금정보_m223, :fee_type_m223), (:주차장명_m224, :소재지지번주소_m224, :주차구획수_m224, :규모구분_m224, :요금정보_m224, :fee_type_m224), (:주차장명_m225, :소재지지번주소_m225, :주차구획수_m225, :규모구분_m225, :요금정보_m225, :fee_type_m225), (:주차장명_m226, :소재지지번주소_m226, :주차구획수_m226, :규모구분_m226, :요금정보_m226, :fee_type_m226), (:주차장명_m227, :소재지지번주소_m227, :주차구획수_m227, :규모구분_m227, :요금정보_m227, :fee_type_m227), (:주차장명_m228, :소재지지번주소_m228, :주차구획수_m228, :규모구분_m228, :요금정보_m228, :fee_type_m228)': (psycopg2.ProgrammingError) can't adapt type 'method'