In [1]:
#라이브러리 불러오기
import math
import os
import time
from datetime import date
import pandas as pd
import requests
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

In [2]:
# API 키 불러오기

load_dotenv()
API_KEY = os.getenv('TAGO_API_KEK')

if API_KEY:
    print(f'API 키 로드 완료: {API_KEY[:6]}...{API_KEY[-4:]}')
else:
    print('env파일에 API키를 설정하세요.')

API 키 로드 완료: fcaf4c...4bf3

### 연결 테스트

In [3]:
BASE_URL = 'https://api.odcloud.kr/api/15059963/v1/uddi:76bba8dc-16b6-4898-96af-e3c056854ec3'

In [4]:
response = requests.get(BASE_URL, params={'serviceKey':API_KEY, '_type':'json'})
response.raise_for_status() # HTTP 오류 목록 알려준다.

In [5]:
print(response.status_code)

200

In [6]:
response = requests.get(BASE_URL, 
                        params={
                            'serviceKey': API_KEY,
                            'page': 1,
                            'perPage': 500,
                            'returnType': 'json',
                            })
response

In [7]:
data = response.json()
data

{'currentCount': 463,
 'data': [{'1등 자동 당첨 건수': 16, '상호': '인터넷 복권판매사이트', '순번': 1, '지역': '서울 서초구'},
  {'1등 자동 당첨 건수': 4, '상호': '오천억복권방', '순번': 2, '지역': '광주 서구'},
  {'1등 자동 당첨 건수': 3, '상호': '로또킹', '순번': 3, '지역': '서울 영등포구'},
  {'1등 자동 당첨 건수': 3, '상호': '오케이상사', '순번': 4, '지역': '서울 서초구'},
  {'1등 자동 당첨 건수': 3, '상호': '부일카서비스', '순번': 5, '지역': '부산 동구'},
  {'1등 자동 당첨 건수': 3, '상호': '메트로센터점', '순번': 6, '지역': '대구 중구'},
  {'1등 자동 당첨 건수': 3, '상호': '복권백화점', '순번': 7, '지역': '경기 파주시'},
  {'1등 자동 당첨 건수': 3, '상호': '로또명당인주점', '순번': 8, '지역': '충남 아산시'},
  {'1등 자동 당첨 건수': 3, '상호': '행복한복권방', '순번': 9, '지역': '전북 전주시 덕진구'},
  {'1등 자동 당첨 건수': 3, '상호': '명당', '순번': 10, '지역': '경남 진주시'},
  {'1등 자동 당첨 건수': 2, '상호': '월드24시', '순번': 11, '지역': '서울 은평구'},
  {'1등 자동 당첨 건수': 2, '상호': '묵동식품', '순번': 12, '지역': '서울 중랑구'},
  {'1등 자동 당첨 건수': 2, '상호': '스파', '순번': 13, '지역': '서울 노원구'},
  {'1등 자동 당첨 건수': 2, '상호': '행운복권방', '순번': 14, '지역': '서울 금천구'},
  {'1등 자동 당첨 건수': 2, '상호': '행운의집', '순번': 15, '지역': '서울 강동구'},
  {'1등 자동 당첨 건수': 2, '상호': '화신상사', '순번': 16, '지역': '부산 동래구'},
  {'1등 자동 당첨 건수': 2, '상호': '복권명당(서부점)', '순번': 17, '지역': '대구 달서구'},
  {'1등 자동 당첨 건수': 2, '상호': '청구마트', '순번': 18, '지역': '대구 북구'},
  {'1등 자동 당첨 건수': 2, '상호': '일등복권편의점', '순번': 19, '지역': '대구 달서구'},
  {'1등 자동 당첨 건수': 2, '상호': '대전우표사', '순번': 20, '지역': '대전 동구'},
  {'1등 자동 당첨 건수': 2, '상호': '제우스테크', '순번': 21, '지역': '대전 서구'},
  {'1등 자동 당첨 건수': 2, '상호': '8888로또', '순번': 22, '지역': '대전 서구'},
  {'1등 자동 당첨 건수': 2, '상호': '북부슈퍼', '순번': 23, '지역': '경기 의정부시'},
  {'1등 자동 당첨 건수': 2, '상호': '한국슈퍼', '순번': 24, '지역': '경기 부천시 오정구'},
  {'1등 자동 당첨 건수': 2, '상호': '내츄럴하우스복권판매점', '순번': 25, '지역': '경기 평택시'},
  {'1등 자동 당첨 건수': 2, '상호': '로또휴게실', '순번': 26, '지역': '경기 용인시 기흥구'},
  {'1등 자동 당첨 건수': 2, '상호': '행운복권방', '순번': 27, '지역': '경기 의정부시'},
  {'1등 자동 당첨 건수': 2, '상호': '신의 축복', '순번': 28, '지역': '경기 남양주시'},
  {'1등 자동 당첨 건수': 2, '상호': '진평양행', '순번': 29, '지역': '강원 강릉시'},
  {'1등 자동 당첨 건수': 2, '상호': '대박마트복권방', '순번': 30, '지역': '충남 아산시'},
  {'1등 자동 당첨 건수': 2, '상호': '흥건슈퍼', '순번': 31, '지역': '전북 전주시 완산구'},
  {'1등 자동 당첨 건수': 2, '상호': '춘향로또', '순번': 32, '지역': '전북 남원시'},
  {'1등 자동 당첨 건수': 2, '상호': '영유통(로또복권)', '순번': 33, '지역': '전북 군산시'},
  {'1등 자동 당첨 건수': 2, '상호': '로또명당', '순번': 34, '지역': '경북 의성군'},
  {'1등 자동 당첨 건수': 2, '상호': '목화휴게소', '순번': 35, '지역': '경남 사천시'},
  {'1등 자동 당첨 건수': 2, '상호': '터미널복권판매점', '순번': 36, '지역': '경남 창원시 마산회원구'},
  {'1등 자동 당첨 건수': 2, '상호': '대청행복복권', '순번': 37, '지역': '경남 김해시'},
  {'1등 자동 당첨 건수': 1, '상호': '복권마을', '순번': 38, '지역': '서울 구로구'},
  {'1등 자동 당첨 건수': 1, '상호': '노다지 노원역점 복권방', '순번': 39, '지역': '서울 노원구'},
  {'1등 자동 당첨 건수': 1, '상호': '보경식품', '순번': 40, '지역': '서울 강북구'},
  {'1등 자동 당첨 건수': 1, '상호': '진흥수퍼', '순번': 41, '지역': '서울 강남구'},
  {'1등 자동 당첨 건수': 1, '상호': '신세계슈퍼', '순번': 42, '지역': '서울 영등포구'},
  {'1등 자동 당첨 건수': 1, '상호': '하나로슈퍼', '순번': 43, '지역': '서울 동대문구'},
  {'1등 자동 당첨 건수': 1, '상호': '그린슈퍼', '순번': 44, '지역': '서울 동대문구'},
  {'1등 자동 당첨 건수': 1, '상호': '삼성마트', '순번': 45, '지역': '서울 강남구'},
  {'1등 자동 당첨 건수': 1, '상호': '여명슈퍼마켓', '순번': 46, '지역': '서울 성북구'},
  {'1등 자동 당첨 건수': 1, '상호': '종합가판제141호', '순번': 47, '지역': '서울 중구'},
  {'1등 자동 당첨 건수': 1, '상호': '종합가로판매점113호패션TV앞', '순번': 48, '지역': '서울 중구'},
  {'1등 자동 당첨 건수': 1, '상호': '가판100호', '순번': 49, '지역': '서울 중구'},
  {'1등 자동 당첨 건수': 1, '상호': '중구-가로가판대-37', '순번': 50, '지역': '서울 중구'},
  {'1등 자동 당첨 건수': 1, '상호': '가판14호', '순번': 51, '지역': '서울 중구'},
  {'1등 자동 당첨 건수': 1, '상호': '가판대', '순번': 52, '지역': '서울 도봉구'},
  {'1등 자동 당첨 건수': 1, '상호': '가로판매점', '순번': 53, '지역': '서울 용산구'},
  {'1등 자동 당첨 건수': 1, '상호': '가로판매점', '순번': 54, '지역': '서울 용산구'},
  {'1등 자동 당첨 건수': 1, '상호': '로또복권판매소', '순번': 55, '지역': '서울 마포구'},
  {'1등 자동 당첨 건수': 1, '상호': '토큰박스', '순번': 56, '지역': '서울 동작구'},
  {'1등 자동 당첨 건수': 1, '상호': '사당', '순번': 57, '지역': '서울 관악구'},
  {'1등 자동 당첨 건수': 1, '상호': '잠실매점', '순번': 58, '지역': '서울 송파구'},
  {'1등 자동 당첨 건수': 1, '상호': '꿈이현실로', '순번': 59, '지역': '서울 중구'},
  {'1등 자동 당첨 건수': 1, '상호': '지원물산', '순번': 60, '지역': '서울 노원구'},
  {'1등 자동 당첨 건수': 1, '상호': '복권방', '순번': 61, '지역': '서울 성북구'},
  {'1등 자동 당첨 건수': 1, '상호': '가판대20호', '순번': 62, '지역': '서울 송파구'},
  {'1등 자동 당첨 건수': 1, '상호': '신가로판매점', '순번': 63, '지역': '서울 중구'},
  {'1등 자동 당첨 건수': 1, '상호': '신일', '순번': 64, '지역': '서울 강서구'},
  {'1등 자동 당첨 건수': 1, '상호': '광나루복권방', '순번': 65, '지역': '서울 광진구'},
  {'1등 자동 당첨 건수': 1, '상호': '씨유 망우점2', '순번': 66, '지역': '서울 중랑구'},
  {'1등 자동 당첨 건수': 1, '상호': '행운복권방', '순번': 67, '지역': '서울 도봉구'},
  {'1등 자동 당첨 건수': 1, '상호': '세명복권', '순번': 68, '지역': '서울 마포구'},
  {'1등 자동 당첨 건수': 1, '상호': '성지로또', '순번': 69, '지역': '서울 송파구'},
  {'1등 자동 당첨 건수': 1, '상호': '살맛나는 세상', '순번': 70, '지역': '서울 동대문구'},
  {'1등 자동 당첨 건수': 1, '상호': '행운식품', '순번': 71, '지역': '서울 관악구'},
  {'1등 자동 당첨 건수': 1, '상호': '고고GOGO로또', '순번': 72, '지역': '서울 광진구'},
  {'1등 자동 당첨 건수': 1, '상호': '고척대박복권&카페', '순번': 73, '지역': '서울 구로구'},
  {'1등 자동 당첨 건수': 1, '상호': '오케이(O.K)로또', '순번': 74, '지역': '서울 도봉구'},
  {'1등 자동 당첨 건수': 1, '상호': '다람쥐로또', '순번': 75, '지역': '서울 마포구'},
  {'1등 자동 당첨 건수': 1, '상호': '행운로또복권방', '순번': 76, '지역': '서울 성북구'},
  {'1등 자동 당첨 건수': 1, '상호': '일등', '순번': 77, '지역': '서울 강동구'},
  {'1등 자동 당첨 건수': 1, '상호': '태양 명당 복권방', '순번': 78, '지역': '서울 금천구'},
  {'1등 자동 당첨 건수': 1, '상호': '정안 복권방', '순번': 79, '지역': '서울 노원구'},
  {'1등 자동 당첨 건수': 1, '상호': '예지행복', '순번': 80, '지역': '서울 양천구'},
  {'1등 자동 당첨 건수': 1, '상호': '꿈이있는 로또점(복권판매점)', '순번': 81, '지역': '서울 은평구'},
  {'1등 자동 당첨 건수': 1, '상호': '쌍둥이네복권방', '순번': 82, '지역': '서울 중구'},
  {'1등 자동 당첨 건수': 1, '상호': '태릉시장복권방', '순번': 83, '지역': '서울 중랑구'},
  {'1등 자동 당첨 건수': 1, '상호': '주황이 복권방', '순번': 84, '지역': '서울 서초구'},
  {'1등 자동 당첨 건수': 1, '상호': '월드로또복권 판매점', '순번': 85, '지역': '서울 강남구'},
  {'1등 자동 당첨 건수': 1, '상호': '행운당', '순번': 86, '지역': '서울 노원구'},
  {'1등 자동 당첨 건수': 1, '상호': '장안평역 3번출구 가판대', '순번': 87, '지역': '서울 동대문구'},
  {'1등 자동 당첨 건수': 1, '상호': '온누리복권', '순번': 88, '지역': '서울 동작구'},
  {'1등 자동 당첨 건수': 1, '상호': '믿음복권방', '순번': 89, '지역': '서울 서대문구'},
  {'1등 자동 당첨 건수': 1, '상호': '지에스(GS)25 신길센트럴점', '순번': 90, '지역': '서울 영등포구'},
  {'1등 자동 당첨 건수': 1, '상호': '크린토피아/최강로또', '순번': 91, '지역': '서울 은평구'},
  {'1등 자동 당첨 건수': 1, '상호': '무지개로또', '순번': 92, '지역': '서울 중구'},
  {'1등 자동 당첨 건수': 1, '상호': '구일 로또 전자담배', '순번': 93, '지역': '서울 구로구'},
  {'1등 자동 당첨 건수': 1, '상호': '해인복권', '순번': 94, '지역': '서울 도봉구'},
  {'1등 자동 당첨 건수': 1, '상호': '가든파이브 복권', '순번': 95, '지역': '서울 송파구'},
  {'1등 자동 당첨 건수': 1, '상호': '굿럭커피', '순번': 96, '지역': '서울 은평구'},
  {'1등 자동 당첨 건수': 1, '상호': '마곡점빵', '순번': 97, '지역': '서울 강서구'},
  {'1등 자동 당첨 건수': 1, '상호': '5번가 로또', '순번': 98, '지역': '서울 송파구'},
  {'1등 자동 당첨 건수': 1, '상호': '복권나라', '순번': 99, '지역': '서울 성동구'},
  {'1등 자동 당첨 건수': 1, '상호': '미나식품(로또판매점)', '순번': 100, '지역': '서울 강서구'},
  {'1등 자동 당첨 건수': 1, '상호': '잉크와복권', '순번': 101, '지역': '서울 강서구'},
  {'1등 자동 당첨 건수': 1, '상호': '복권나라', '순번': 102, '지역': '서울 광진구'},
  {'1등 자동 당첨 건수': 1, '상호': '현대복권방', '순번': 103, '지역': '서울 동대문구'},
  {'1등 자동 당첨 건수': 1, '상호': '용꿈돼지꿈', '순번': 104, '지역': '서울 마포구'},
  {'1등 자동 당첨 건수': 1, '상호': '하나복권(가로판매점)', '순번': 105, '지역': '서울 영등포구'},
  {'1등 자동 당첨 건수': 1, '상호': '편의점사랑', '순번': 106, '지역': '서울 강서구'},
  {'1등 자동 당첨 건수': 1, '상호': '가로판매점', '순번': 107, '지역': '서울 영등포구'},
  {'1등 자동 당첨 건수': 1, '상호': '천하명당초량점', '순번': 108, '지역': '부산 동구'},
  {'1등 자동 당첨 건수': 1, '상호': '복권방', '순번': 109, '지역': '부산 사하구'},
  {'1등 자동 당첨 건수': 1, '상호': '왕대박', '순번': 110, '지역': '부산 동래구'},
  {'1등 자동 당첨 건수': 1, '상호': '돈벼락맞는곳', '순번': 111, '지역': '부산 동구'},
  {'1등 자동 당첨 건수': 1, '상호': '뉴빅마트', '순번': 112, '지역': '부산 기장군'},
  {'1등 자동 당첨 건수': 1, '상호': '우정식품', '순번': 113, '지역': '부산 동래구'},
  {'1등 자동 당첨 건수': 1, '상호': '성광복권명당', '순번': 114, '지역': '부산 연제구'},
  {'1등 자동 당첨 건수': 1, '상호': '청솔서점', '순번': 115, '지역': '부산 사하구'},
  {'1등 자동 당첨 건수': 1, '상호': '행운로또', '순번': 116, '지역': '부산 동래구'},
  {'1등 자동 당첨 건수': 1, '상호': '로또복권', '순번': 117, '지역': '부산 사하구'},
  {'1등 자동 당첨 건수': 1, '상호': '빅세일복권방', '순번': 118, '지역': '부산 부산진구'},
  {'1등 자동 당첨 건수': 1, '상호': '로터리복권방', '순번': 119, '지역': '부산 서구'},
  {'1등 자동 당첨 건수': 1, '상호': '백금당', '순번': 120, '지역': '부산 중구'},
  {'1등 자동 당첨 건수': 1, '상호': '돼지복권명당', '순번': 121, '지역': '부산 기장군'},
  {'1등 자동 당첨 건수': 1, '상호': '럭키', '순번': 122, '지역': '부산 북구'},
  {'1등 자동 당첨 건수': 1, '상호': '모라행운로또', '순번': 123, '지역': '부산 사상구'},
  {'1등 자동 당첨 건수': 1, '상호': '복권판매점 명지국제신도시점', '순번': 124, '지역': '부산 강서구'},
  {'1등 자동 당첨 건수': 1, '상호': '평생꽃길대연점', '순번': 125, '지역': '부산 남구'},
  {'1등 자동 당첨 건수': 1, '상호': '행운나눔', '순번': 126, '지역': '부산 사하구'},
  {'1등 자동 당첨 건수': 1, '상호': '요기어때', '순번': 127, '지역': '부산 해운대구'},
  {'1등 자동 당첨 건수': 1, '상호': '행운 로또복권', '순번': 128, '지역': '부산 해운대구'},
  {'1등 자동 당첨 건수': 1, '상호': '국물이시원해', '순번': 129, '지역': '부산 금정구'},
  {'1등 자동 당첨 건수': 1, '상호': '금두꺼비 복권방', '순번': 130, '지역': '부산 동래구'},
  {'1등 자동 당첨 건수': 1, '상호': '다시 꿈꾸는 미래 동행복권', '순번': 131, '지역': '부산 부산진구'},
  {'1등 자동 당첨 건수': 1, '상호': '하늘복권방', '순번': 132, '지역': '부산 해운대구'},
  {'1등 자동 당첨 건수': 1, '상호': '천하제일명당', '순번': 133, '지역': '부산 부산진구'},
  {'1등 자동 당첨 건수': 1, '상호': '복드림 복권방', '순번': 134, '지역': '부산 북구'},
  {'1등 자동 당첨 건수': 1, '상호': '동해마트', '순번': 135, '지역': '부산 동래구'},
  {'1등 자동 당첨 건수': 1, '상호': '돈벼락맞는곳 부산서면점', '순번': 136, '지역': '부산 부산진구'},
  {'1등 자동 당첨 건수': 1, '상호': '기장슈퍼', '순번': 137, '지역': '부산 기장군'},
  {'1등 자동 당첨 건수': 1, '상호': '천하명당복권', '순번': 138, '지역': '대구 북구'},
  {'1등 자동 당첨 건수': 1, '상호': '거봉마트(원고개시장)', '순번': 139, '지역': '대구 서구'},
  {'1등 자동 당첨 건수': 1, '상호': '씨스페이스 성서계대점', '순번': 140, '지역': '대구 달서구'},
  {'1등 자동 당첨 건수': 1, '상호': '서재강변로또', '순번': 141, '지역': '대구 달성군'},
  {'1등 자동 당첨 건수': 1, '상호': '복권명당', '순번': 142, '지역': '대구 수성구'},
  {'1등 자동 당첨 건수': 1, '상호': '황금대박점', '순번': 143, '지역': '대구 수성구'},
  {'1등 자동 당첨 건수': 1, '상호': '로또명당(유가테크노점)', '순번': 144, '지역': '대구 달성군'},
  {'1등 자동 당첨 건수': 1, '상호': '반달커피대구침산점', '순번': 145, '지역': '대구 북구'},
  {'1등 자동 당첨 건수': 1, '상호': '일등커피로또판매점', '순번': 146, '지역': '대구 수성구'},
  {'1등 자동 당첨 건수': 1, '상호': '행복한복권', '순번': 147, '지역': '대구 수성구'},
  {'1등 자동 당첨 건수': 1, '상호': '럭키로또', '순번': 148, '지역': '대구 수성구'},
  {'1등 자동 당첨 건수': 1, '상호': '와이에스컴퍼니', '순번': 149, '지역': '대구 남구'},
  {'1등 자동 당첨 건수': 1, '상호': '복권명당신기점', '순번': 150, '지역': '대구 동구'},
  {'1등 자동 당첨 건수': 1, '상호': '한솔복권&마트', '순번': 151, '지역': '인천 미추홀구'},
  {'1등 자동 당첨 건수': 1, '상호': '복권전문점', '순번': 152, '지역': '인천 부평구'},
  {'1등 자동 당첨 건수': 1, '상호': '제일슈퍼', '순번': 153, '지역': '인천 연수구'},
  {'1등 자동 당첨 건수': 1, '상호': '24시슈퍼', '순번': 154, '지역': '인천 부평구'},
  {'1등 자동 당첨 건수': 1, '상호': 'L마트', '순번': 155, '지역': '인천 서구'},
  {'1등 자동 당첨 건수': 1, '상호': '한마음병원앞버스매표소', '순번': 156, '지역': '인천 계양구'},
  {'1등 자동 당첨 건수': 1, '상호': '인현동지하가판', '순번': 157, '지역': '인천 중구'},
  {'1등 자동 당첨 건수': 1, '상호': '명동럭키로또', '순번': 158, '지역': '인천 연수구'},
  {'1등 자동 당첨 건수': 1, '상호': '한국인세계대박복권', '순번': 159, '지역': '인천 연수구'},
  {'1등 자동 당첨 건수': 1, '상호': '로또복권방', '순번': 160, '지역': '인천 부평구'},
  {'1등 자동 당첨 건수': 1, '상호': '우리복권', '순번': 161, '지역': '인천 남동구'},
  {'1등 자동 당첨 건수': 1, '상호': '노다지로또', '순번': 162, '지역': '인천 서구'},
  {'1등 자동 당첨 건수': 1, '상호': '희망복권', '순번': 163, '지역': '인천 서구'},
  {'1등 자동 당첨 건수': 1, '상호': '황금복권방', '순번': 164, '지역': '인천 연수구'},
  {'1등 자동 당첨 건수': 1, '상호': '하영', '순번': 165, '지역': '인천 서구'},
  {'1등 자동 당첨 건수': 1, '상호': '로터리 클럽', '순번': 166, '지역': '인천 미추홀구'},
  {'1등 자동 당첨 건수': 1, '상호': '동인천황금로또', '순번': 167, '지역': '인천 중구'},
  {'1등 자동 당첨 건수': 1, '상호': '행복드림로또판매점', '순번': 168, '지역': '인천 강화군'},
  {'1등 자동 당첨 건수': 1, '상호': '대박복권판매점', '순번': 169, '지역': '인천 남동구'},
  {'1등 자동 당첨 건수': 1, '상호': '행복드림 복권', '순번': 170, '지역': '인천 서구'},
  {'1등 자동 당첨 건수': 1, '상호': '이유복권', '순번': 171, '지역': '인천 서구'},
  {'1등 자동 당첨 건수': 1, '상호': '홍이복권방', '순번': 172, '지역': '인천 서구'},
  {'1등 자동 당첨 건수': 1, '상호': '복덩이 로또', '순번': 173, '지역': '인천 연수구'},
  {'1등 자동 당첨 건수': 1, '상호': '윤', '순번': 174, '지역': '인천 미추홀구'},
  {'1등 자동 당첨 건수': 1, '상호': '돈방석', '순번': 175, '지역': '인천 남동구'},
  {'1등 자동 당첨 건수': 1, '상호': '골든벨 복권판매점', '순번': 176, '지역': '인천 미추홀구'},
  {'1등 자동 당첨 건수': 1, '상호': '대박신화복권판매점', '순번': 177, '지역': '인천 미추홀구'},
  {'1등 자동 당첨 건수': 1, '상호': '황금돼지', '순번': 178, '지역': '인천 미추홀구'},
  {'1등 자동 당첨 건수': 1, '상호': '노다지복권방백운점', '순번': 179, '지역': '광주 남구'},
  {'1등 자동 당첨 건수': 1, '상호': '역전복권방', '순번': 180, '지역': '광주 광산구'},
  {'1등 자동 당첨 건수': 1, '상호': '해피+24시편의점', '순번': 181, '지역': '광주 북구'},
  {'1등 자동 당첨 건수': 1, '상호': '동키호테편의점', '순번': 182, '지역': '광주 서구'},
  {'1등 자동 당첨 건수': 1, '상호': '광주도서유통', '순번': 183, '지역': '광주 남구'},
  {'1등 자동 당첨 건수': 1, '상호': '알리바이', '순번': 184, '지역': '광주 광산구'},
  {'1등 자동 당첨 건수': 1, '상호': '복권나라', '순번': 185, '지역': '광주 북구'},
  {'1등 자동 당첨 건수': 1, '상호': '천하명당복권방', '순번': 186, '지역': '광주 서구'},
  {'1등 자동 당첨 건수': 1, '상호': '차밍플라워 로또', '순번': 187, '지역': '광주 광산구'},
  {'1등 자동 당첨 건수': 1, '상호': '복권나라(중흥점)', '순번': 188, '지역': '광주 북구'},
  {'1등 자동 당첨 건수': 1, '상호': '광주공항로또', '순번': 189, '지역': '광주 광산구'},
  {'1등 자동 당첨 건수': 1, '상호': '현대마트점', '순번': 190, '지역': '광주 서구'},
  {'1등 자동 당첨 건수': 1, '상호': '복권나라(매곡동)', '순번': 191, '지역': '광주 북구'},
  {'1등 자동 당첨 건수': 1, '상호': '금집복권', '순번': 192, '지역': '광주 북구'},
  {'1등 자동 당첨 건수': 1, '상호': '대전하이퍼', '순번': 193, '지역': '대전 중구'},
  {'1등 자동 당첨 건수': 1, '상호': '복권명당', '순번': 194, '지역': '대전 서구'},
  {'1등 자동 당첨 건수': 1, '상호': '로또복권방', '순번': 195, '지역': '대전 서구'},
  {'1등 자동 당첨 건수': 1, '상호': '로또편의점', '순번': 196, '지역': '대전 유성구'},
  {'1등 자동 당첨 건수': 1, '상호': '로또명당 황금돼지', '순번': 197, '지역': '대전 중구'},
  {'1등 자동 당첨 건수': 1, '상호': '마치복권', '순번': 198, '지역': '대전 서구'},
  {'1등 자동 당첨 건수': 1, '상호': '까치로또판매점', '순번': 199, '지역': '대전 서구'},
  {'1등 자동 당첨 건수': 1, '상호': '왕대박 복권판매점', '순번': 200, '지역': '대전 유성구'},
  {'1등 자동 당첨 건수': 1, '상호': '대박로또', '순번': 201, '지역': '대전 중구'},
  {'1등 자동 당첨 건수': 1, '상호': '베스토아(용전2호)', '순번': 202, '지역': '대전 동구'},
  {'1등 자동 당첨 건수': 1, '상호': '한꿈복권방', '순번': 203, '지역': '울산 중구'},
  {'1등 자동 당첨 건수': 1, '상호': '보람복권방', '순번': 204, '지역': '울산 남구'},
  {'1등 자동 당첨 건수': 1, '상호': '우리들공업탑점', '순번': 205, '지역': '울산 남구'},
  {'1등 자동 당첨 건수': 1, '상호': '로또25시', '순번': 206, '지역': '울산 남구'},
  {'1등 자동 당첨 건수': 1, '상호': '로또명당진하점', '순번': 207, '지역': '울산 울주군'},
  {'1등 자동 당첨 건수': 1, '상호': '지에스25(울산우정선경점)로또', '순번': 208, '지역': '울산 중구'},
  {'1등 자동 당첨 건수': 1, '상호': '세븐일레븐 울산동진점', '순번': 209, '지역': '울산 동구'},
  {'1등 자동 당첨 건수': 1, '상호': '예가유통', '순번': 210, '지역': '울산 북구'},
  {'1등 자동 당첨 건수': 1, '상호': '또로또', '순번': 211, '지역': '울산 남구'},
  {'1등 자동 당첨 건수': 1, '상호': '동성슈퍼', '순번': 212, '지역': '울산 울주군'},
  {'1등 자동 당첨 건수': 1, '상호': '영화유통(1등복권방)', '순번': 213, '지역': '울산 남구'},
  {'1등 자동 당첨 건수': 1, '상호': '셀피아', '순번': 214, '지역': '울산 북구'},
  {'1등 자동 당첨 건수': 1, '상호': '노다지복권방', '순번': 215, '지역': '경기 시흥시'},
  {'1등 자동 당첨 건수': 1, '상호': '송정복권', '순번': 216, '지역': '경기 군포시'},
  {'1등 자동 당첨 건수': 1, '상호': '대운복권', '순번': 217, '지역': '경기 성남시 중원구'},
  {'1등 자동 당첨 건수': 1, '상호': '천하명당복권방', '순번': 218, '지역': '경기 수원시 팔달구'},
  {'1등 자동 당첨 건수': 1, '상호': '해피마트', '순번': 219, '지역': '경기 의왕시'},
  {'1등 자동 당첨 건수': 1, '상호': '운수대통', '순번': 220, '지역': '경기 군포시'},
  {'1등 자동 당첨 건수': 1, '상호': '리버스 편의점', '순번': 221, '지역': '경기 하남시'},
  {'1등 자동 당첨 건수': 1, '상호': '공원슈퍼', '순번': 222, '지역': '경기 수원시 장안구'},
  {'1등 자동 당첨 건수': 1, '상호': '터미널식품', '순번': 223, '지역': '경기 의정부시'},
  {'1등 자동 당첨 건수': 1, '상호': '복권판매점', '순번': 224, '지역': '경기 고양시 일산서구'},
  {'1등 자동 당첨 건수': 1, '상호': '버스표가판점', '순번': 225, '지역': '경기 안양시 동안구'},
  {'1등 자동 당첨 건수': 1, '상호': '바로전산', '순번': 226, '지역': '경기 광명시'},
  {'1등 자동 당첨 건수': 1, '상호': '만물전파사', '순번': 227, '지역': '경기 남양주시'},
  {'1등 자동 당첨 건수': 1, '상호': '로또N삭스', '순번': 228, '지역': '경기 의정부시'},
  {'1등 자동 당첨 건수': 1, '상호': '웅진', '순번': 229, '지역': '경기 수원시 영통구'},
  {'1등 자동 당첨 건수': 1, '상호': '다들복권방', '순번': 230, '지역': '경기 부천시 오정구'},
  {'1등 자동 당첨 건수': 1, '상호': '카베', '순번': 231, '지역': '경기 부천시 원미구'},
  {'1등 자동 당첨 건수': 1, '상호': '복권나라', '순번': 232, '지역': '경기 오산시'},
  {'1등 자동 당첨 건수': 1, '상호': '로토피아', '순번': 233, '지역': '경기 광명시'},
  {'1등 자동 당첨 건수': 1, '상호': '로또명당상동점', '순번': 234, '지역': '경기 부천시 소사구'},
  {'1등 자동 당첨 건수': 1, '상호': '그린마트', '순번': 235, '지역': '경기 성남시 분당구'},
  {'1등 자동 당첨 건수': 1, '상호': '명당골복권방', '순번': 236, '지역': '경기 수원시 권선구'},
  {'1등 자동 당첨 건수': 1, '상호': '로또복권방', '순번': 237, '지역': '경기 시흥시'},
  {'1등 자동 당첨 건수': 1, '상호': '머니머니', '순번': 238, '지역': '경기 시흥시'},
  {'1등 자동 당첨 건수': 1, '상호': '로또명당', '순번': 239, '지역': '경기 시흥시'},
  {'1등 자동 당첨 건수': 1, '상호': '광성슈퍼', '순번': 240, '지역': '경기 이천시'},
  {'1등 자동 당첨 건수': 1, '상호': '황금복권마트', '순번': 241, '지역': '경기 이천시'},
  {'1등 자동 당첨 건수': 1, '상호': '행운복권방', '순번': 242, '지역': '경기 김포시'},
  {'1등 자동 당첨 건수': 1, '상호': '세븐일레븐 평내지원점', '순번': 243, '지역': '경기 남양주시'},
  {'1등 자동 당첨 건수': 1, '상호': '우리로또복권', '순번': 244, '지역': '경기 연천군'},
  {'1등 자동 당첨 건수': 1, '상호': '서울로또', '순번': 245, '지역': '경기 의정부시'},
  {'1등 자동 당첨 건수': 1, '상호': '복권나라', '순번': 246, '지역': '경기 포천시'},
  {'1등 자동 당첨 건수': 1, '상호': '올인 (all in)', '순번': 247, '지역': '경기 화성시'},
  {'1등 자동 당첨 건수': 1, '상호': '드림복권방', '순번': 248, '지역': '경기 수원시 권선구'},
  {'1등 자동 당첨 건수': 1, '상호': '세븐일레븐 안산역점', '순번': 249, '지역': '경기 안산시 단원구'},
  {'1등 자동 당첨 건수': 1, '상호': '로또유통', '순번': 250, '지역': '경기 안산시 단원구'},
  {'1등 자동 당첨 건수': 1, '상호': '로또판매선부점', '순번': 251, '지역': '경기 안산시 단원구'},
  {'1등 자동 당첨 건수': 1, '상호': '행운을주는로또판매점', '순번': 252, '지역': '경기 안산시 단원구'},
  {'1등 자동 당첨 건수': 1, '상호': '순살로복권', '순번': 253, '지역': '경기 의왕시'},
  {'1등 자동 당첨 건수': 1, '상호': '복돼지복권방', '순번': 254, '지역': '경기 화성시'},
  {'1등 자동 당첨 건수': 1, '상호': '꿈이있는로또', '순번': 255, '지역': '경기 여주시'},
  {'1등 자동 당첨 건수': 1, '상호': '마두5번출구가판로또', '순번': 256, '지역': '경기 고양시 일산동구'},
  {'1등 자동 당첨 건수': 1, '상호': '아이지에이마트 오산무지개점', '순번': 257, '지역': '경기 오산시'},
  {'1등 자동 당첨 건수': 1, '상호': '로또복권슈퍼(국제꽃화원)', '순번': 258, '지역': '경기 의정부시'},
  {'1등 자동 당첨 건수': 1, '상호': '평택포승점로또', '순번': 259, '지역': '경기 평택시'},
  {'1등 자동 당첨 건수': 1, '상호': '100억로또점', '순번': 260, '지역': '경기 김포시'},
  {'1등 자동 당첨 건수': 1, '상호': '153나눔로또편의점', '순번': 261, '지역': '경기 성남시 분당구'},
  {'1등 자동 당첨 건수': 1, '상호': '로또복권', '순번': 262, '지역': '경기 오산시'},
  {'1등 자동 당첨 건수': 1, '상호': '주몽동명', '순번': 263, '지역': '경기 용인시 수지구'},
  {'1등 자동 당첨 건수': 1, '상호': '천하명당', '순번': 264, '지역': '경기 파주시'},
  {'1등 자동 당첨 건수': 1, '상호': '바른', '순번': 265, '지역': '경기 하남시'},
  {'1등 자동 당첨 건수': 1, '상호': '동탄복권방', '순번': 266, '지역': '경기 화성시'},
  {'1등 자동 당첨 건수': 1, '상호': '온누리로또', '순번': 267, '지역': '경기 수원시 권선구'},
  {'1등 자동 당첨 건수': 1, '상호': '비휴 로또', '순번': 268, '지역': '경기 오산시'},
  {'1등 자동 당첨 건수': 1, '상호': '복권전문점', '순번': 269, '지역': '경기 시흥시'},
  {'1등 자동 당첨 건수': 1, '상호': '하남시청 세븐일레븐 로또', '순번': 270, '지역': '경기 하남시'},
  {'1등 자동 당첨 건수': 1, '상호': '교통카드충전소', '순번': 271, '지역': '경기 용인시 처인구'},
  {'1등 자동 당첨 건수': 1, '상호': '로또편의점', '순번': 272, '지역': '경기 김포시'},
  {'1등 자동 당첨 건수': 1, '상호': '새희망복권', '순번': 273, '지역': '경기 화성시'},
  {'1등 자동 당첨 건수': 1, '상호': '화랑로또판매점', '순번': 274, '지역': '경기 화성시'},
  {'1등 자동 당첨 건수': 1, '상호': '1등로또', '순번': 275, '지역': '경기 화성시'},
  {'1등 자동 당첨 건수': 1, '상호': '로또복권편의점', '순번': 276, '지역': '경기 수원시 권선구'},
  {'1등 자동 당첨 건수': 1, '상호': '정통복권방', '순번': 277, '지역': '경기 수원시 팔달구'},
  {'1등 자동 당첨 건수': 1, '상호': '남문시장', '순번': 278, '지역': '경기 수원시 팔달구'},
  {'1등 자동 당첨 건수': 1, '상호': '로또카페', '순번': 279, '지역': '경기 평택시'},
  {'1등 자동 당첨 건수': 1, '상호': '오남 로또택배', '순번': 280, '지역': '경기 남양주시'},
  {'1등 자동 당첨 건수': 1, '상호': '행운복권', '순번': 281, '지역': '경기 군포시'},
  {'1등 자동 당첨 건수': 1, '상호': '새말편의점', '순번': 282, '지역': '경기 안성시'},
  {'1등 자동 당첨 건수': 1, '상호': '신의한수', '순번': 283, '지역': '경기 화성시'},
  {'1등 자동 당첨 건수': 1, '상호': '씨유 포천인생역전점', '순번': 284, '지역': '경기 포천시'},
  {'1등 자동 당첨 건수': 1, '상호': '고양행복복권', '순번': 285, '지역': '경기 고양시 덕양구'},
  {'1등 자동 당첨 건수': 1, '상호': '씨월드', '순번': 286, '지역': '경기 남양주시'},
  {'1등 자동 당첨 건수': 1, '상호': '월산리주고받는로또', '순번': 287, '지역': '경기 남양주시'},
  {'1등 자동 당첨 건수': 1, '상호': '한방복권', '순번': 288, '지역': '경기 파주시'},
  {'1등 자동 당첨 건수': 1, '상호': '대운로또(씨스페이스)', '순번': 289, '지역': '경기 화성시'},
  {'1등 자동 당첨 건수': 1, '상호': '한아름 복권', '순번': 290, '지역': '경기 김포시'},
  {'1등 자동 당첨 건수': 1, '상호': '드림 복권판매점', '순번': 291, '지역': '경기 부천시 원미구'},
  {'1등 자동 당첨 건수': 1, '상호': '천하명당', '순번': 292, '지역': '경기 안산시 단원구'},
  {'1등 자동 당첨 건수': 1, '상호': '지에스25 안성칠곡', '순번': 293, '지역': '경기 안성시'},
  {'1등 자동 당첨 건수': 1, '상호': '황금복권판매점', '순번': 294, '지역': '경기 양주시'},
  {'1등 자동 당첨 건수': 1, '상호': '365대박찬스', '순번': 295, '지역': '경기 양주시'},
  {'1등 자동 당첨 건수': 1, '상호': '동탄호수복권', '순번': 296, '지역': '경기 화성시'},
  {'1등 자동 당첨 건수': 1, '상호': '동행복권(로또복권)', '순번': 297, '지역': '경기 남양주시'},
  {'1등 자동 당첨 건수': 1, '상호': '대운상사', '순번': 298, '지역': '경기 남양주시'},
  {'1등 자동 당첨 건수': 1, '상호': '영앤로또', '순번': 299, '지역': '경기 남양주시'},
  {'1등 자동 당첨 건수': 1, '상호': '1번지복권방', '순번': 300, '지역': '경기 성남시 중원구'},
  {'1등 자동 당첨 건수': 1, '상호': '수원역로또맛집', '순번': 301, '지역': '경기 수원시 팔달구'},
  {'1등 자동 당첨 건수': 1, '상호': '아이지에이마트 동명사랑점', '순번': 302, '지역': '경기 안산시 단원구'},
  {'1등 자동 당첨 건수': 1, '상호': '똥광 로또 복권방', '순번': 303, '지역': '경기 안산시 단원구'},
  {'1등 자동 당첨 건수': 1, '상호': '당첨쑥쑥복권', '순번': 304, '지역': '경기 의왕시'},
  {'1등 자동 당첨 건수': 1, '상호': '한빛3단지 천지인', '순번': 305, '지역': '경기 파주시'},
  {'1등 자동 당첨 건수': 1, '상호': '탄현대박로또복권', '순번': 306, '지역': '경기 파주시'},

In [8]:
data['data'][0]

{'1등 자동 당첨 건수': 16, '상호': '인터넷 복권판매사이트', '순번': 1, '지역': '서울 서초구'}

In [9]:
BASE_URL = 'https://api.odcloud.kr/api/15059963/v1/uddi:76bba8dc-16b6-4898-96af-e3c056854ec3'
ROWS_PER_PAGE = 1000
REQUEST_TIMEOUT = 10

In [10]:
BASE_DIR = os.getcwd()  # 현재 위치
OUTPUT_DIR = os.path.join(BASE_DIR, 'output')
OUTPUT_PATH = os.path.join(OUTPUT_DIR, 'lottery_region.csv')

In [11]:
DB_URL = 'postgresql://postgres:1234@localhost:5432/lotterydb'
TABLE_NAME = 'lottery_region'

print(f'csv저장경로 : {OUTPUT_PATH}')

csv저장경로 : c:\Users\Administrator\bigdata2026\fastapi\07_빅데이터수집시스템개발\output\lottery_region.csv

In [12]:
total_count = data['totalCount']
per_page = 50 
total_pages = math.ceil(total_count / per_page)

In [13]:
print(f"전체 데이터 개수: {total_count}개")
print(f"계산된 총 페이지 수: {total_pages}개")

전체 데이터 개수: 463개
계산된 총 페이지 수: 10개

### 전체 데이터 수집

In [14]:
all_items = []

for page_no in range(1, total_pages+1):
    params={
        'serviceKey' : API_KEY,
        'page' : page_no,
        'perPage' : per_page,
        '_type' : 'json'
    }

    response = requests.get(BASE_URL, params=params,timeout=REQUEST_TIMEOUT)
    response.raise_for_status()

    page_items = response.json().get('data', [])

    if not page_items:
        print(f'{page_no} / {total_pages} 페이지 : 페이지가 없음')
        continue


    if isinstance(page_items, dict):
        page_items = [page_items]  

    all_items.extend(page_items)

    print(f'{page_no} / {total_pages} 페이지 수집 완료 -> 누적 {len(all_items):,}건')

    time.sleep(0.2)

print(f'전체 수집 완료 : {len(all_items):,}건')

1 / 10 페이지 수집 완료 -> 누적 50건
2 / 10 페이지 수집 완료 -> 누적 100건
3 / 10 페이지 수집 완료 -> 누적 150건
4 / 10 페이지 수집 완료 -> 누적 200건
5 / 10 페이지 수집 완료 -> 누적 250건
6 / 10 페이지 수집 완료 -> 누적 300건
7 / 10 페이지 수집 완료 -> 누적 350건
8 / 10 페이지 수집 완료 -> 누적 400건
9 / 10 페이지 수집 완료 -> 누적 450건
10 / 10 페이지 수집 완료 -> 누적 463건
전체 수집 완료 : 463건

In [15]:
df_raw = pd.DataFrame(all_items)
print(f'데이터프레임의 크기 : {df_raw.shape}')
print(f'컬럼 목록 : {df_raw.columns.tolist()}')

데이터프레임의 크기 : (463, 4)
컬럼 목록 : ['1등 자동 당첨 건수', '상호', '순번', '지역']

In [16]:
df_raw.head()

   1등 자동 당첨 건수           상호  순번       지역
0           16  인터넷 복권판매사이트   1   서울 서초구
1            4       오천억복권방   2    광주 서구
2            3          로또킹   3  서울 영등포구
3            3        오케이상사   4   서울 서초구
4            3       부일카서비스   5    부산 동구

### 데이터 전처리

In [17]:
df_raw.drop('순번', axis=1, inplace=True)

In [18]:
df_raw

     1등 자동 당첨 건수           상호          지역
0             16  인터넷 복권판매사이트      서울 서초구
1              4       오천억복권방       광주 서구
2              3          로또킹     서울 영등포구
3              3        오케이상사      서울 서초구
4              3       부일카서비스       부산 동구
..           ...          ...         ...
458            1  로또플렉스 시티세븐점  경남 창원시 성산구
459            1         땅땅낚시      경남 거제시
460            1          복슈퍼      경남 김해시
461            1         만물가게      제주 제주시
462            1       돈벼락 복권      제주 제주시

[463 rows x 3 columns]

### 시도 컬럼 추가

In [19]:
df_raw['시도'] = df_raw['지역'].str[:2]

df_raw

     1등 자동 당첨 건수           상호          지역  시도
0             16  인터넷 복권판매사이트      서울 서초구  서울
1              4       오천억복권방       광주 서구  광주
2              3          로또킹     서울 영등포구  서울
3              3        오케이상사      서울 서초구  서울
4              3       부일카서비스       부산 동구  부산
..           ...          ...         ...  ..
458            1  로또플렉스 시티세븐점  경남 창원시 성산구  경남
459            1         땅땅낚시      경남 거제시  경남
460            1          복슈퍼      경남 김해시  경남
461            1         만물가게      제주 제주시  제주
462            1       돈벼락 복권      제주 제주시  제주

[463 rows x 4 columns]

### '시도'컬럼 중 서울 데이터만 추출

In [20]:
df_2 = df_raw[df_raw['시도'] == '서울']

In [21]:
df_2

     1등 자동 당첨 건수           상호       지역  시도
0             16  인터넷 복권판매사이트   서울 서초구  서울
2              3          로또킹  서울 영등포구  서울
3              3        오케이상사   서울 서초구  서울
10             2        월드24시   서울 은평구  서울
11             2         묵동식품   서울 중랑구  서울
..           ...          ...      ...  ..
102            1        현대복권방  서울 동대문구  서울
103            1        용꿈돼지꿈   서울 마포구  서울
104            1  하나복권(가로판매점)  서울 영등포구  서울
105            1        편의점사랑   서울 강서구  서울
106            1        가로판매점  서울 영등포구  서울

[78 rows x 4 columns]

### PostgreSQL 저장

In [22]:
# 함수 정의
def save_to_postgresql(df_2, db_url, table_name):
    """DataFrame을 PostgreSQL 테이블로 저장하는 함수"""
    df_save = df_2.copy()

    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)

    engine = create_engine(db_url)

    # DB 연결 테스트
    with engine.connect() as conn:
        version = conn.execute(text('SELECT version();')).fetchone()[0]
        print('PostgreSQL 연결 성공!')
        print(version[:80] + '...')

    # DataFrame을 DB테이블로 저장
    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize=1000,
        method='multi'
    )

    # 저장 건수 확인
    with engine.connect() as conn:
        saved_count = conn.execute(text(f'SELECT COUNT(*) FROM {table_name};')).fetchone()[0]

    print(f'저장 완료: {saved_count:,}행')
    print(f'DB: lotterydb / table: {table_name}')

In [23]:
save_to_postgresql(df_2, DB_URL, TABLE_NAME)

PostgreSQL 연결 성공!
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
저장 완료: 78행
DB: lotterydb / table: lottery_region